### ISSUE TITLE
“无拼音纯汉字”大文件转“chinese-pyim”提示“不好意思，发生了错误：未将对象引用设置到对象的实例。”

### ISSUE THREAD

**Issue by saccohuo** [studyzy/imewlconverter#10]
“无拼音纯汉字”大文件转“chinese-pyim”提示“不好意思，发生了错误：未将对象引用设置到对象的实例”。

文件约有10万条词库，转换到最后出来这个提示。设置中只更改了高级设置中的词频设置为“Google搜索”，其他设置未做修改。 @tumashu 

我试过比较小的文件按照同样的设置不会有问题。 

![image](https://cloud.githubusercontent.com/assets/13887263/14873083/16eee4f6-0d25-11e6-928e-4c589be9f67d.png)

下面是我的词库文件。

[pseudo-original-hundred-thousand.txt](https://github.com/studyzy/imewlconverter/files/239648/pseudo-original-hundred-thousand.txt)

**Comment by tumashu** [comment]
@saccohuo 如果你着急，可以用 pyim-article2dict-word 命令试试

**Comment by saccohuo** [comment]
我的文件就是一个词库哎，如果再使用这种分词，会不会跟原本的词库有一定出入呢？

**Comment by tumashu** [comment]
你的文件不需要分词了。。。。直接可以转换

**Comment by saccohuo** [comment]
soga，话说这样子出来的带词频吗？

**Comment by tumashu** [comment]
不带。。。

**Comment by saccohuo** [comment]
@tumashu 呆神如果什么时候有空修复一下的时候，艾特我一下哈

**Comment by tumashu** [comment]
这个不是我的项目，况且我也不会.net呀

在 2016-05-18 20:17:15，husky <notifications@github.com> 写道：


@tumashu 呆神如果什么时候有空修复一下的时候，艾特我一下哈

**Comment by saccohuo** [comment]
Soga，我以为这部分是你搞的呢，你只是提供了个格式哈，那我问一下作者。

**Comment by tumashu** [comment]
哈哈，我只是给作者提交了一个 feature 需求，作者给我添加了这个功能

**Comment by saccohuo** [comment]
呆神，我有个文件用 `pyim-article2dict-word` 转换出来是这个样子，是什么情况哎。 @tumashu 

![image](https://cloud.githubusercontent.com/assets/13887263/15627883/e4098894-2524-11e6-83ce-18d63c76c08b.png)

源文件：

[pseudo-original-hundred-thousand.txt](https://github.com/studyzy/imewlconverter/files/287752/pseudo-original-hundred-thousand.txt)


转换之后的文件：

[FinishStage-14384bRx-pseudo-original-hundred-thousand.txt](https://github.com/studyzy/imewlconverter/files/287753/FinishStage-14384bRx-pseudo-original-hundred-thousand.txt)

**Comment by studyzy** [comment]
新版本已经修复该问题
