### ISSUE TITLE
数组越界错误

### ISSUE THREAD

**Issue by demybugs** [studyzy/imewlconverter#100]
我一个象棋五笔词库(.TXT)格式。红方的词条可以转换成功并导入成微软五笔自定义词库：
“
rwfw 兵八进八
rwff 兵八进二
rwfv 兵八进九
rwfu 兵八进六
......
”
但是，当把这些词条复制一份，转换成象棋黑方的棋谱记法：
“
rwfw 兵8进8
rwff 兵8进2
rwfv 兵8进9
rwfu 兵8进6
......
”
则会转换失败，提示越界错误。
在微软五笔自定义词条里是可以一条一条地加入这些的：rwfw 兵8进8 rwff 兵8进2......
请问是不是显示词条里不能有数字（比如程序没有考虑过“兵8进8”这种中文与数字混合的字符串）？谢谢！

**Comment by studyzy** [comment]
高级设置，过滤设置中，默认是过滤了包含数字的词的，把那个过滤取消即可。
