### ISSUE TITLE
Gboard导入方法（转载）

### ISSUE THREAD

**Issue by ricepeak** [studyzy/imewlconverter#103]
https://www.jianshu.com/p/00373c2d2bd6

**Comment by studyzy** [comment]
麻烦能提供一个有可导入词库功能的gboard apk给我吗？我下载的都没有词库导入功能

**Comment by ricepeak** [comment]
https://apkpure.com/cn/gboard-the-google-keyboard/com.google.android.inputmethod.latin
APKPure的安装包，和Play同步的。

**Comment by cswhatsgit** [comment]
> 
> 
> https://www.jianshu.com/p/00373c2d2bd6

折腾了半天，结果导入以后词都归类到了日语下面，测试了一下，中文输入法不调取日语词典。您有这个问题吗？

**Comment by sologuy** [comment]
> > https://www.jianshu.com/p/00373c2d2bd6
> 
> 折腾了半天，结果导入以后词都归类到了日语下面，测试了一下，中文输入法不调取日语词典。您有这个问题吗？

你可能是格式没弄对， 那个中间是制表符不是缩进

**Comment by cswhatsgit** [comment]
> > > https://www.jianshu.com/p/00373c2d2bd6
> > 
> > 
> > 折腾了半天，结果导入以后词都归类到了日语下面，测试了一下，中文输入法不调取日语词典。您有这个问题吗？
> 
> 你可能是格式没弄对， 那个中间是制表符不是缩进

哎？原文不是说“是制表符缩进不是空格”吗？我是word里按一下tab然后复制粘贴的，那您怎么弄的呀？

**Comment by dongfengweixiao** [comment]
> > https://www.jianshu.com/p/00373c2d2bd6
> 
> 折腾了半天，结果导入以后词都归类到了日语下面，测试了一下，中文输入法不调取日语词典。您有这个问题吗？

因为这个文档里面说的有点错误（也可能是新版本的Gboard改变了格式），每个编码之间的分隔符选择“无”，编码汉字词频之间的分隔符选择TAB即可。

**Comment by caliban511** [comment]
> 
> 
> > https://www.jianshu.com/p/00373c2d2bd6
> 
> 折腾了半天，结果导入以后词都归类到了日语下面，测试了一下，中文输入法不调取日语词典。您有这个问题吗？

导入成日语的这位兄弟，我也遇到过。
转化完后最上面要加：
# Gboard Dictionary version:1
# From OS
你是不是只加了第一行，忘了加第二行？

**Comment by klren0312** [comment]
方法就是
在Gboard里导出词库, 查看格式
然后更具格式来把自己现有的词库改下, ok

**Comment by Jas0nG0ng** [comment]
如何把gboard的词库转换为搜狗的词库？

**Comment by mingchau** [comment]
> > https://www.jianshu.com/p/00373c2d2bd6
> 
> 折腾了半天，结果导入以后词都归类到了日语下面，测试了一下，中文输入法不调取日语词典。您有这个问题吗？

字典导入跑到日语里面应该是因为导出的字典文件有bom，格式转换成无BOM的UTF-8就OK了、

**Comment by iukv** [comment]
[User Dictionary Manager (UDM)](https://play.google.com/store/apps/details?id=com.usr.dict.mgr) 
把系统调成目标语言，就能导入对应语言的词库。至于导入格式，可以在用户字典中输入若干键值对，通过上面软件导出观察一下。
> 这里所谓词库其实就是 Android 的用户字典。发现从 Gboard 进入的用户字典和上面软件进入的用户字典（系统原生的，国内一些UI隐藏了其入口，但上面那个软件可以访问和管理）并非一个，但 Gboard 完美调用。目前发现的能完美支持Android用户字典的软件也就 Gboard 了。

**Comment by studyzy** [comment]
最新v2.9版本已经支持Gboard词库的导入导出，欢迎大家使用。
