### ISSUE TITLE
转换成功，但是导出的txt文件是空文件

### ISSUE THREAD

**Issue by Sunyu-ahu** [studyzy/imewlconverter#107]
netframe安装了，转换的原文件是bin类型的，转换成搜狗txt，显示成功，也导出成功，但是打开文件，显示是空文件，没有任何文本。

**Comment by studyzy** [comment]
可能是你的bin词库有问题，一般bin词库大小1~3M左右，如果你的bin词库10~20M甚至更大那就有问题。
