### ISSUE TITLE
QQ拼音qcel格式转换不全

### ISSUE THREAD

**Issue by StressState** [studyzy/imewlconverter#108]
转换成功但只输出了5条结果，原词库有4000+条吧
[测试词库.zip](https://github.com/studyzy/imewlconverter/files/3637457/default.zip)

**Comment by yfdyh000** [comment]
已修复。是因包含中英混拼词条。

https://ci.appveyor.com/project/yfdyh000/imewlconverter/builds/43025933/job/ho27vxa58ttxu5ia/artifacts
https://github.com/yfdyh000/imewlconverter/releases/tag/3.0-20220326

**Comment by tumuyan** [comment]
> 是因包含中英混拼词条。

我不太确认目前深蓝处理中英文混拼的情况到底是怎么样的？
过去我用纯文本转rime拼音，发现含英文词条无法编码，于是非常粗糙地添加了一个编码方式——英文可以选择直接编码，可以选择添加_前缀。（对rime拼音输入而言，前缀是非常有必要的，可以避免对普通拼音词条的干扰）
但是我对其他格式的词条转换完全不清楚。目前其他格式的转换，混拼词条有在正常处理，还是直接跳过呢？
能不能使用一个统一的办法——譬如我现在添加的_前缀作为英文部分的深蓝的内部编码，然后输出时根据用户的设定决定是否添加这个前缀？
