### ISSUE TITLE
请问如何把搜狗的词库导入到win10的微软拼音中呢?

### ISSUE THREAD

**Issue by xishijt** [studyzy/imewlconverter#109]
我现在把搜狗的.bin词库备份转换成了win10微软拼.dat文件,但是在微软的自学习还有用户自定义短语中都没法导入词库.

**Comment by studyzy** [comment]
是不是数据量太大了，微软拼音自定义短语一次能够导入的词条数比较有限。你先试一试把搜狗bin导出为文本，看能成功不。然后选取其中的几千条再转换成微软拼音。

**Comment by dreistein543** [comment]
我这里也无法导入。提示 `文件格式错误或文件已损坏`

具体信息：
系统： win 10 1903
深蓝版本：2.6
搜狗输入法版本：9.5

P.S. 用notepad++打开导出的 dat 文件，发现与 win10 自己导出的结果有区别（虽然绝大多数都是乱码，但是发现深蓝导出的 dat 至少多一个开头 `mschxudp` 即使更换原词库也出现，而 win10 自己导入的结果则没有）

**Comment by hongzk** [comment]
遇到同样的问题。
系统： win10 1909
深蓝：2.6

**Comment by studyzy** [comment]
经过测试，没有发现这样的问题。建议再用2.7版试一试。
