### ISSUE TITLE
分享一种安卓版Gboard导入词库不丢失数据的方法

### ISSUE THREAD

**Issue by EsuRt** [studyzy/imewlconverter#111]
在Gboard中直接导入词库，会出现词条丢失的现象，下面是安卓版Gboard导入词库不丢失数据的方法。

**原理**：直接修改Gboard词库的数据库，需要root权限。

**具体步骤**：
1、复制PersonalDictionary.db到电脑，PersonalDictionary.db在/data/data/com.google.android.inputmethod.latin/databases目录下，并在电脑上将转换好的文本文件导入数据库；
2、将修改后的PersonalDictionary.db重新复制回原目录，并覆盖保存，如果目录下有PersonalDictionary.db-shm和PersonalDictionary.db-wal，删除这两个文件；
3、查看Gboard的字典中有没有导入的词库。

**附**：这里有一个已经修改好的PersonalDictionary.db，嫌麻烦的可以直接用这个词库，词库包括【搜狗】成语俗语、【搜狗】古诗词名句、【搜狗】宋词精选、【搜狗】唐诗300首、【搜狗】网络流行新词（截至2019年11月3日）、【紫光】紫光词库11.01（由sanwsw制作的综合词库，截至2019年11月3日，具体请参考[http://www.unispim.com/wordlib/wordlib_detail.php?id=66](http://www.unispim.com/wordlib/wordlib_detail.php?id=66)），词库已经进行去重处理，同时去除拉丁文等非中文字符（导入Gboard后，拉丁文等字符无法被正确识别），最后共计873769条。

![1](https://user-images.githubusercontent.com/15177069/68468457-0a812b80-0253-11ea-8d1f-4763ff11711a.png)

**下载**：[PersonalDictionary.zip](https://github.com/studyzy/imewlconverter/files/3824064/PersonalDictionary.zip)

**Comment by dongfengweixiao** [comment]
给你点赞，不过需要root权限，就不操作了。

**Comment by cswhatsgit** [comment]
放入.db后输入法正常使用，但是在设置里点personal dictionary想打开看看都有什么词条Gboard就崩溃，等了一晚上也还是这样。然后试了试把/databases下的文件全部清空只留PersonalDictionary.db也还是崩溃。也不知道导入成功了没有 /(ㄒoㄒ)/~~

**Comment by EsuRt** [comment]
> 放入.db后输入法正常使用，但是在设置里点personal dictionary想打开看看都有什么词条Gboard就崩溃，等了一晚上也还是这样。然后试了试把/databases下的文件全部清空只留PersonalDictionary.db也还是崩溃。也不知道导入成功了没有 /(ㄒoㄒ)/~~

这个问题我之前也遇到过，可以尝试通过以下方式解决：
1、安装一个其他的输入法，并切换到该输入法，使得Gboard处于不被调用的状态；
2、在应用管理中清除Gboard的缓存和数据；
3、重复导入词库的步骤；
4、切换至Gboard，查看导入的词库，如果成功导入了，词库中是能看到具体条目的，不会出现崩溃的情况。

**Comment by wegood9** [comment]
这里再提供一个解决复制后崩溃的方法：复制时不要用cp或者文件管理器，使用`dd if=PersonalDictionary.db of=/data/data/com.google.android.inputmethod.latin/databases/PersonalDictionary.db`命令

**Comment by studyzy** [comment]
最新v2.9版本支持Gboard词库的导入导出，欢迎使用。

**Comment by 1045925330** [comment]
我导入了16w条进去，然后发现一万一千条后面的好像都不生效😰
