### ISSUE TITLE
建议导入“要转换的词库”显示源码表格式

### ISSUE THREAD

**Issue by zgdlime** [studyzy/imewlconverter#113]
建议导入“要转换的词库”显示源码表格式，需求再由用户选择：
![无标题](https://user-images.githubusercontent.com/13276912/69960622-e14b7680-1544-11ea-8d8e-66d1c4d99d35.png)

**Comment by studyzy** [comment]
这是个转换工具，不是显示工具，所以不考虑显示源码格式。
