### ISSUE TITLE
能支持txt转搜狗bin吗

### ISSUE THREAD

**Issue by njuzss** [studyzy/imewlconverter#115]
需要从百度转到搜狗，百度导出的是txt格式，软件下载下来貌似没有从txt转成bin的选项

**Comment by studyzy** [comment]
不支持。可以导出为搜狗拼音txt，然后在搜狗输入法中导入文本词库即可。

**Comment by njuzss** [comment]
搜狗输入法没有导入文本词库入口哎，我看都是强制为bin类型，麻烦能指点下吗。一直没找到，是不是新版的去掉了？

**Comment by studyzy** [comment]
![微信截图_20191217115238](https://user-images.githubusercontent.com/1635408/70963648-18349700-20c4-11ea-8b02-a2a0826446d5.png)
