### ISSUE TITLE
关于搜狗词库toWin10微软拼音自定短语，能否添加个功能在转换时把全拼编码转成双拼的？

### ISSUE THREAD

**Issue by wutongskype** [studyzy/imewlconverter#117]
由于俺是用微软双拼的，但是用深蓝把搜狗的转到Win10微软拼音自定短语的时候那个编码是全拼的，作者大大能否给添加个转成微软双拼的功能？或者有其他办法能把词库的编码转一下吗？

**Comment by studyzy** [comment]
我找了一下，没找到微软双拼的编码映射表，如果您能提供映射表，我可以把微软双拼支持进去。
这是小鹤双拼的全拼-》双拼 映射表：https://raw.githubusercontent.com/studyzy/imewlconverter/master/src/ImeWlConverterCore/Resources/XiaoheShuangpin.txt

**Comment by viazure** [comment]
> 我找了一下，没找到微软双拼的编码映射表，如果您能提供映射表，我可以把微软双拼支持进去。
> 这是小鹤双拼的全拼-》双拼 映射表：https://raw.githubusercontent.com/studyzy/imewlconverter/master/src/ImeWlConverterCore/Resources/XiaoheShuangpin.txt

作者，你好。我保存有一份 `.plist` 格式的[映射表](https://github.com/viazure/ShuangPinPlistFiles)，Windows 端用 [plistEditor](https://www.icopybot.com/plist-editor.htm)可以打开，里面的内容是 XML 格式的，你可以看一下吗？迫切需要微软双拼和自然码的，非常感谢。

**Comment by dpk4g** [comment]
在这个问题上追加个提问，还望解惑：
本意是想把搜狗词库转为小鹤双拼词库，用深蓝可以成功转为win10输入法并使用，但在把这个已经转好的双拼词库再转为Gboard可用的词库就不行了——因为输入法的用户自定义短语界面会卡死，无法导出。
请问有如何能实现Gboard可用的双拼词库方案？

**Comment by studyzy** [comment]
@dpk4g Gboard太新了，可能暂时无法实现。

**Comment by studyzy** [comment]
@viazure 你能不能把你的PList文件直接转换为文本格式，然后放在GitHub上？我下载不了，也运行不了plist editor.

**Comment by dpk4g** [comment]
> @dpk4g Gboard太新了，可能暂时无法实现。

的确是新，Gboard一直在优化中。试过导入过全拼的词库还不完整，a-c起头的词都没有导入。
有没有可能在其他常见输入法中加入可编码为双拼的方案？因为巨硬的输入法会卡死无法导出已有的双拼方案，所以用其他输入法替代导出可能也是个曲线的办法吧。

**Comment by viazure** [comment]
> @viazure 你能不能把你的PList文件直接转换为文本格式，然后放在GitHub上？我下载不了，也运行不了plist editor.

我用 plistEditor 将 XML 格式的文本复制出来了。放到 [XML](https://github.com/viazure/ShuangPinPlistFiles/tree/master/XML) 文件夹下了。顺便打包了一份放到奶牛快传里。
> TA分享了1个文件给你，在奶牛快传首页（cowtransfer.com）输入取件码：whgqy5 (24小时内有效) 查看文件列表，或直接点击取件链接: https://c-t.work/s/d124f87e928844 查看文件列表

**Comment by studyzy** [comment]
双拼编码已经解决。

**Comment by zyf0330** [comment]
请问如何转换全拼到双拼呢，我有 Gboard 的全拼词库，但是没找到什么在输出时转换拼音编码的选项

**Comment by viazure** [comment]
> 请问如何转换全拼到双拼呢，我有 Gboard 的全拼词库，但是没找到什么在输出时转换拼音编码的选项

你选择目标词库为Win10拼音（自定义短语）后，自动会弹出拼音配置设置，然后再选择你需要的编码方案就行了

**Comment by zyf0330** [comment]
[转换到 Gboard 微软双拼](https://gist.github.com/zyf0330/5874455087bc69708f07ff13d12890a5)
