### ISSUE TITLE
最新版五笔编码转化不对

### ISSUE THREAD

**Issue by JUST-INTJ** [studyzy/imewlconverter#118]
V2.6版本 任何编码转换为五笔编码规则都是不对的（还是拼音规则，都一模一样）。然后下载一个历史版V2.3转换的是对的。

**Comment by JUST-INTJ** [comment]
源词库在各大输入法平台下载（QQ 百度 搜狗 )，目标是五笔 86版  （linux下用）
发现转换的是 拼音+汉字，又测试了转换为其他的。结果都是 拼音+汉字 。

弄了好久，还是不可以！ 最后下载个历史版本的，才可以正常。

也许是我电脑问题，我是在win7系统上操作的。

**Comment by studyzy** [comment]
![image](https://user-images.githubusercontent.com/1635408/72578580-63370980-3911-11ea-8b4e-c3eb62199a79.png)
没发现有这个问题呢。生成的就是五笔编码啊。

**Comment by jsshwqz** [comment]
![QQ截图20240826201550](https://github.com/user-attachments/assets/452d1cb1-ba94-4242-b952-ee6dd19218d5)
![QQ截图20240826201612](https://github.com/user-attachments/assets/10566750-5ad3-476d-8519-1206ef742b23)
试了换地址，换别的格式 也是不行，
