### ISSUE TITLE
命令行下的bug

### ISSUE THREAD

**Issue by cabbage89** [studyzy/imewlconverter#12]
`private WordLibraryList Filter(WordLibraryList list)
        {
            var result = new WordLibraryList();
            foreach (WordLibrary wordLibrary in list)
            {
                if (IsKeep(wordLibrary))
                {
//这个地方需要检测空,命令行下面报错
                    if (ReplaceFilters != null)
                        foreach (IReplaceFilter replaceFilter in ReplaceFilters)
                        {
                            replaceFilter.Replace(wordLibrary);
                        }
                    if (wordLibrary.Word != string.Empty)
                        result.Add(wordLibrary);
                }
            }
            return result;
        }`

ime wl converter\ime wl converter\mainbody.cs

**Comment by studyzy** [comment]
谢谢你的指出并修正。
