### ISSUE TITLE
在Linux下字体部分是乱码的

### ISSUE THREAD

**Issue by kjhuanhao** [studyzy/imewlconverter#120]
**截图**
![](https://cdn.jsdelivr.net/gh/kjhuanhao/cdn/blog/rime.png
)

**Comment by studyzy** [comment]
请问您是通过什么样的方式在Linux下实现GUI界面的？一般来说，Linux推荐使用dotnet 命令行方式进行词库转换。

**Comment by kjhuanhao** [comment]
我是arch用户,这应该来自其他用户做的软件

**Comment by studyzy** [comment]
请问在哪里下载的，我也试一试。

**Comment by studyzy** [comment]
应该是Mono的版本，建议还是用dotnet core吧，命令行更方便。
