### ISSUE TITLE
mac下无法使用

### ISSUE THREAD

**Issue by LEFrost** [studyzy/imewlconverter#122]
[frost@local] ~/Downloads/imewlconverter_Linux_Mac ❯ dotnet ImeWlConverterCmd.dll -?
zsh: no matches found: -?
其他参数类似，获取不到arguments

**Comment by studyzy** [comment]
zsh不知道为什么对参数的支持不是很好。运行：
>dotnet ImeWlConverterCmd.dll "-?"
就可以了。
