### ISSUE TITLE
转换时运行出错

### ISSUE THREAD

**Issue by lgq-lzw** [studyzy/imewlconverter#124]
Win10x64，装有.net4.x框架，装百度、QQ、搜狗、华宇几个拼音输入法。运行深蓝词库转换工具，无论源输入法与目标输入法选择什么，点击“转换”按钮均弹窗显示“不好意思，发生了错误：索引超出了数组界限。”结果窗口显示“索引超出了数组界限。”，然而源输入法词库可以正常导入到对应的输入法当中使用，导入过程也无出错提示。尝试了直至2.7版为止最后几个版本的深蓝转换器都这样。手动将词库文件缩减到两三个词条仍然这样。

**Comment by studyzy** [comment]
没遇到这种情况。能否提供一个你要转换的词库，然后你的源输入法和目标输入法是什么。我在本地试一试。

**Comment by lgq-lzw** [comment]
好的。提供几个，都是文本词库。都出现楼顶贴的情况。
---百度
阿崩叫狗	a'beng'jiao'gou'	2
阿超着裤	a'chao'zhuo'ku'	2
阿贵买布	a'gui'mai'bu'	2
阿均卖大头	a'jun'mai'da'tou'	2
阿兰嫁阿瑞	a'lan'jia'a'rui'	2
阿兰卖猪	a'lan'mai'zhu'	2
阿妈都唔认得	a'ma'dou'wu'ren'de'	2
阿嫲	a'ma'	2
阿茂整饼	a'mao'zheng'bing'	2

---QQ&Sogou
a'beng'jiao'gou 阿崩叫狗 2
a'chao'zhuo'ku 阿超着裤 2
a'gui'mai'bu 阿贵买布 2
a'jun'mai'da'tou 阿均卖大头 2
a'lan'jia'a'rui 阿兰嫁阿瑞 2
a'lan'mai'zhu 阿兰卖猪 2
a'ma'dou'wu'ren'de 阿妈都唔认得 2
a'ma 阿嫲 2
a'mao'zheng'bing 阿茂整饼 2

---华宇
阿崩叫狗	a'beng'jiao'gou	1
阿超着裤	a'chao'zhuo'ku	1
阿贵买布	a'gui'mai'bu	1
阿均卖大头	a'jun'mai'da'tou	1
阿兰嫁阿瑞	a'lan'jia'a'rui	1
阿兰卖猪	a'lan'mai'zhu	1
阿妈都唔认得	a'ma'dou'wu'ren'de	1
阿嫲	a'ma	1
阿茂整饼	a'mao'zheng'bing	1

---手心
阿崩叫狗	a'beng'jiao'gou	2
阿超着裤	a'chao'zhuo'ku	2
阿贵买布	a'gui'mai'bu	2
阿均卖大头	a'jun'mai'da'tou	2
阿兰嫁阿瑞	a'lan'jia'a'rui	2
阿兰卖猪	a'lan'mai'zhu	2
阿妈都唔认得	a'ma'dou'wu'ren'de	2
阿嫲	a'ma	2
阿茂整饼	a'mao'zheng'bing	2

---必应
阿崩叫狗 a beng jiao gou 
阿超着裤 a chao zhuo ku 
阿贵买布 a gui mai bu 
阿均卖大头 a jun mai da tou 
阿兰嫁阿瑞 a lan jia a rui 
阿兰卖猪 a lan mai zhu 
阿妈都唔认得 a ma dou wu ren de 

---谷歌
阿崩叫狗	2	a beng jiao gou
阿超着裤	2	a chao zhuo ku
阿贵买布	2	a gui mai bu
阿均卖大头	2	a jun mai da tou
阿兰嫁阿瑞	2	a lan jia a rui
阿兰卖猪	2	a lan mai zhu
阿妈都唔认得	2	a ma dou wu ren de

---微软拼音2007/2010
阿崩叫狗  a1 beng1 jiao4 gou3
阿超着裤  a1 chao1 zhuo2 ku4
阿贵买布  a1 gui4 mai3 bu4
阿均卖大头  a1 jun1 mai4 da4 tou2
阿兰嫁阿瑞  a1 lan2 jia4 a1 rui4
阿兰卖猪  a1 lan2 mai4 zhu1
阿妈都唔认得  a1 ma1 dou1 wu2 ren4 de2
阿嫲  a1 ma2
阿茂整饼  a1 mao4 zheng3 bing3

**Comment by studyzy** [comment]
@lgq-lzw 你的源词库文件不是由输入法直接导出生成的吧？ 词库文件的编码不对，文件内容中的格式不对，都会导致解析失败。
请使用输入法导出的词库文件作为数据源。

**Comment by lgq-lzw** [comment]
很奇怪你说我这格式不对。
要是把输入法导出的词库直接作为数据源，我干脆直接使用输入法词库，还用转换吗？就是要用自定义词条，所以才手动编辑。就是嫌每个输入法都手动处理，才考虑采用转换工具。目的是手动处理一个输入法自定义词库比手动处理多个要省时。但现在没办法，暂时智能手动处理多个。
我是上述输入法里头先手动自定义几个词条，再导出为文件。然后分别打开各个导出的词库文件，按其格式复制多条，再把每条的文字内容和注音更换为我的自定义词条，格式完全用输入法导出的，连分隔符都照用。手动编辑完的词库可以0出错导入回各种输入法当中。所以格式是不会错的。
我需要处理的词条有上千条，每次更新处理都很费时，上面回复里只抽取9条。但即使是只用1条，用当前版本的深蓝照样出错，所以我才来反馈。

**Comment by studyzy** [comment]
@lgq-lzw 你把你想转换，但是转换又报错的的某个完整词库用邮件附件的形式发给我一下吧，我本地电脑试一试。邮箱：studyzy(a)163.com
