### ISSUE TITLE
关于命令行版本导出词频的一些疑问

### ISSUE THREAD

**Issue by mritd** [studyzy/imewlconverter#127]
1、我发现 UI 版本是有 4 个选项，其中 按字频计算 选项在命令行帮助文档中没有找到如何设置

```sh
对于导入词库不包含词频，而导出时需要指定词频，可以通过-r:命令指定词频的生成方式，支持的有：
-r:baidu  根据该词语在百度搜索的结果数量决定词频
-r:google  根据该词语在Google搜索的结果数量决定词频(需翻墙)
-r:数字  指定一个固定数字的词频
```

2、测试词频通过百度生成确实无比慢...想问一下这个是否是单线程处理，同时有没有增加并发查询的可能

**Comment by mritd** [comment]
@studyzy 经过测试似乎百度对于查询是有验证码的，所以需要设置一些必要的 HTTP HEADER，我看代码里似乎没有设置 https://github.com/studyzy/imewlconverter/blob/6d7f01c5fa5660c3ee702fbf3ee427ca5d456bdf/src/ImeWlConverterCore/Helpers/HttpHelper.cs#L17

所以目前猜测可能是遇到了百度验证码问题导致查询缓慢(不懂 C#，只能猜测)

**Comment by studyzy** [comment]
可能是百度网站改版了，毕竟这是多年前写的方法，当时适用。最近比较忙，有时间把你说的这几个问题都验证处理一遍。

**Comment by mritd** [comment]
@studyzy 好的 感谢，我测试增加这几个 Header 就可以(增加 gzip 后需要自己解码 gzip 压缩的 body)

https://github.com/mritd/sgdict/blob/3647af993637f015d96cb361ab80be5bfc3b8154/pkg/wordrank/wordrank.go#L12

**Comment by ayalhw** [comment]
这个问题似乎仍未修复

**Comment by mritd** [comment]
百渡、google 在大批量查询都有限制，除非弄动态代理池去跑，然而我当时花了 50 大洋也没把我自己的词库跑完

**Comment by ayalhw** [comment]
> 百渡、google 在大批量查询都有限制，除非弄动态代理池去跑，然而我当时花了 50 大洋也没把我自己的词库跑完

那就没办法了……

**Comment by xianghongai** [comment]
@mritd  请教一下，导出为 Rime 用的词库，如何关闭词频？
