### ISSUE TITLE
一次性转换过多数据会导致OOM

### ISSUE THREAD

**Issue by zxeoc** [studyzy/imewlconverter#129]
我这里测试一次性转换171个搜狗细胞词库，每个文件100K到10M不等，总体不到100M，会报System.OutOfMemoryException异常。是在“生成词频”这个步骤报的。
大体参数：从搜狗细胞词库转为Rime中州韵linux拼音
词条过滤：不过滤
合并多个文件到一个文件

edit：不好意思，刚才搞错量词库的数量和大小。

**Comment by studyzy** [comment]
可以用命令行一个一个的转，也可以在界面上选择流转换模式，减少内存使用。

**Comment by zxeoc** [comment]
刚刚又测试了一下，没有问题了，谢谢
