### ISSUE TITLE
已经安装了 .Net Core SDK 还是不能免 DLL 运行？

### ISSUE THREAD

**Issue by ivysrono** [studyzy/imewlconverter#131]
.Net Core SDK 3.1.201 x64

**Comment by studyzy** [comment]
不是很明白，你是怎么运行的？麻烦把命令和结果截图出来看看？

**Comment by ivysrono** [comment]
![图片](https://user-images.githubusercontent.com/2649544/78473359-98196680-7772-11ea-9fa5-df67b5246e35.png)

忘说了，Win10 x64
如果不用压缩包里的dll，命令行和界面都没有任何反应。

**Comment by studyzy** [comment]
核心转换逻辑都在dll里面，exe只是一个WinForm的封装而已，所以都是必不可少的，不能扔掉dll文件。

**Comment by ivysrono** [comment]
原来如此，多谢。
