### ISSUE TITLE
release 2.8 搜狗拼音转换成win10微软拼音（自定义短语）未生成导出文件

### ISSUE THREAD

**Issue by lycor1s** [studyzy/imewlconverter#132]
用2.7版本可以成功导出bat文件，但是2.8版本转换之后没有文件生成。

**Comment by leonardo-pes** [comment]
> 用2.7版本可以成功导出bat文件，但是2.8版本转换之后没有文件生成。

一开始我也以为未生成dat文件  最后发现生成在程序所在的磁盘根目录下了

**Comment by lycor1s** [comment]
> > 用2.7版本可以成功导出bat文件，但是2.8版本转换之后没有文件生成。
> 
> 一开始我也以为未生成dat文件 最后发现生成在程序所在的磁盘根目录下了

还真是。。

**Comment by MarkussLugia** [comment]
同，生成在根目录下了...
![Z 2MP_M6R {UW`AZP_@EVR](https://user-images.githubusercontent.com/30189537/82438816-39af0a00-9acc-11ea-9e85-3710250b4452.png)

**Comment by studyzy** [comment]
下一个版本修正这个问题。
