### ISSUE TITLE
macos自带输入法导入词库可能导致chrome使用非中文输入法时异常卡顿！！！

### ISSUE THREAD

**Issue by XYZliang** [studyzy/imewlconverter#133]
如题，半年前通过此项目导入了搜狗的词库到mac系统中供mac自带中文输入法使用，从此，英文状态下，使用chrome浏览器的网页中任何输入框输入的时候都会异常卡顿（比如百度的搜索框，网站的登陆框），chrome cpu占用飙满，chrome假死几秒后恢复正常，而Safari却无比正常（要是Safari也出问题我就有正当理由找天才吧换电脑了hhh）。
此问题折磨了我大半年，无论是关闭所有chrome插件，退出谷歌账号，重装chrome，恢复模式直接重装，还是恢复模式全部抹除再重装，进入安全模式，关闭所以后台应用、输入监控、辅助功能权限全部都无法解决。

天气慢慢热了起来，脾气也越发暴躁hhh，今天实在受不了，又一步步来检测问题到底出在哪。新建了一个用户，进去使用时却发现chrome丝滑流畅，没有了之前的问题。进入安全模式，发现问题依旧存在。结合apple支持页面关于排查错误的说明和自己的判断（apple支持真是个好东西），此情况很可能与icloud中某些同步的文件或者设置有关，于是便在设置中进行寻找可能的原因。。说来也巧，直接就点进了键盘设置，之前导入的词库赫然映入眼帘，想起作者之前说的导入词库在iPhone设置里进入就会很卡，果断删除了所有导入的词库，然后此困扰我大半年的问题终于解决！！！！！！！！！

 **该项目是个很好的项目，这个bug也不是出在项目身上**，我发布这个只是想提醒那些试图给mac自带输入法（iPhone自带输入法）的童鞋门提个醒，，三思啊啊啊啊啊啊啊啊，大概率是苹果和谷歌的锅（edge也有这个问题，而其它软件都正常，说明Chromium内核也有锅）。**希望作者能提醒后面的童鞋，在你有mac的情况下，请勿尝试给mac/iphone系统导入词库，或者尽量少导入，除非你不用chrome。**（卑微软工学生狗，不用chrome怎么行）

_ps：不是电脑问题，估计也不是个例，毕竟推理的“有理有据”，而且系统也重装n次了。。。macbook pro13寸2019顶配，肯定是hold得住的，锅在系统和chrome上。_

**Comment by studyzy** [comment]
我现在是Mac+搜狗输入法，似乎没什么问题。

**Comment by XYZliang** [comment]
> 我现在是Mac+搜狗输入法，似乎没什么问题。

对的。使用第三方输入法不会出现问题，因为他不会掉用系统的词库，用的是他自己的。
问题出现在苹果自带输入法的英文模式下（在自动匹配词库）
