### ISSUE TITLE
转 搜狗五笔.bin 到TXT，发生错误

### ISSUE THREAD

**Issue by inoton** [studyzy/imewlconverter#135]
感谢您开发的工具。在转换搜狗五笔.bin词库到TXT时，发生以下错误提示：“不好意思，发生了错误：引发类型为：System.OutOfMemoryException的异常。” 尝试了很多次，依旧是这个提示。
使用的是 深蓝词库转换2.8 ，wb.bin :链接:pan.baidu.com/s/1l540748EQJeiE1B4KlGzJA 提取码: ABC3 邮箱: inoton <at> sina.com 谢谢！

**Comment by studyzy** [comment]
我似乎并没有做搜狗五笔bin词库的导入导出。你选的是"搜狗拼音bin"吧？

**Comment by inoton** [comment]
感谢回复，是的。选的是"搜狗拼音bin"

**Comment by studyzy** [comment]
暂不支持搜狗五笔bin
