### ISSUE TITLE
搜狗拼音词库转化为微软自学习词库的文件导入失败

### ISSUE THREAD

**Issue by XZventus** [studyzy/imewlconverter#136]
如图，文件转化成功后无法被导入
![TIM截图20200612180243](https://user-images.githubusercontent.com/46597361/84491499-3bd54480-acd7-11ea-8496-a7028c70979e.jpg)
![TIM截图20200612180314](https://user-images.githubusercontent.com/46597361/84491503-3d9f0800-acd7-11ea-8b1d-49855f16495f.jpg)
![TIM截图20200612180357](https://user-images.githubusercontent.com/46597361/84491508-3ed03500-acd7-11ea-9db2-ae7ccde6ae4f.jpg)

**Comment by studyzy** [comment]
麻烦能否将搜狗拼音备份词库bin文件和你转换后的微软拼音自学习词库.dat文件发给我？我本地试一试，看是什么原因。studyzy(a)163.com

**Comment by studyzy** [comment]
已通过QQ联系解决。
