### ISSUE TITLE
请问软件性能的限制是什么

### ISSUE THREAD

**Issue by snowoneyebrow** [studyzy/imewlconverter#139]
感觉软件运行比较慢 没有充分发挥硬件的性能

**Comment by studyzy** [comment]
是。基本没有启用多线程。而且用户词库量也不会特别的大。但是要说慢，好像您是第一个提软件慢的。

**Comment by lkyu-ly** [comment]
我也想求一下多线程支持：接近40w行的词库转换一次竟需要接近半小时

**Comment by yfdyh000** [comment]
> 我也想求一下多线程支持：接近40w行的词库转换一次竟需要接近半小时

@lkyu-ly 能提供这种词库的下载和指明转换方式吗。听上去不正常。

**Comment by lkyu-ly** [comment]
> @lkyu-ly 能提供这种词库的下载和指明转换方式吗。听上去不正常。

是我的问题，使用的的词库有问题，选择的转换方式不对，已经放弃该词库文件，感谢。
