### ISSUE TITLE
转换超大词库的时候OutOfMemoryException

### ISSUE THREAD

**Issue by jrokr** [studyzy/imewlconverter#140]
这个词库大小为341M，我想把它从全拼转双拼，然后就报错了，分割文件也失败报错。
![Snipaste_2020-07-28_17-57-16](https://user-images.githubusercontent.com/16099156/88652127-fd67dd80-d0fc-11ea-841a-442c3443a9a7.png)

**Comment by studyzy** [comment]
麻烦将词库文件发给我邮箱或者网盘共享出来，我本地调试一下。

**Comment by linewwei** [comment]
309M 转换超大词库的时候OutOfMemoryException

**Comment by jrokr** [comment]
蓝奏云盘：https://www.lanzous.com/iPXhaewkvna    密码:f5bn
天翼云盘：https://cloud.189.cn/t/F36b6rB3ieMj（访问码：3hwk）

**Comment by linewwei** [comment]
链接: https://pan.baidu.com/s/14oIPJ6cSGrL7WFUPvr-Pdg 提取码: i3h6   309m 搜狗词库

**Comment by linewwei** [comment]
![image](https://user-images.githubusercontent.com/3862575/88753580-2042d200-d18f-11ea-87be-3e0b7ded6400.png)
断点的行 内存溢出，文件太大  能不能分断加载到内存中呢？

**Comment by studyzy** [comment]
我试了确实不行，你这需求太变态，不具有普遍性，代码上要改成流转换还比较复杂。暂时不考虑针对这个需求进行更改了。建议用个64G的Windows服务器试一试，也许就不会报错了。

**Comment by zhufengyun** [comment]
![image](https://user-images.githubusercontent.com/5113936/97077565-7a7cf300-1617-11eb-9bc3-b15653b43578.png)
从源码编译，添加并选择x64平台即可

1/1     SuperRimev20.3.dat      转换完成，耗时：54.4605241秒
转换完成,共转换5987613个

**Comment by jrokr** [comment]
> ![image](https://user-images.githubusercontent.com/5113936/97077565-7a7cf300-1617-11eb-9bc3-b15653b43578.png)
> 从源码编译，添加并选择x64平台即可
> 
> 1/1 SuperRimev20.3.dat 转换完成，耗时：54.4605241秒
> 转换完成,共转换5987613个

成功了，感谢！
