### ISSUE TITLE
非拼音被吞

### ISSUE THREAD

**Issue by liuxilu** [studyzy/imewlconverter#145]
希望能有选项不转换拼音
[test.zip, Win10拼音自定义短语, 含有一条 ms -> Microsoft](https://github.com/studyzy/imewlconverter/files/5334157/test.zip)

**Comment by studyzy** [comment]
在高级选项中有词条过滤的选项，默认是把带英文字幕的词汇过滤的。可以去掉这个过滤。

**Comment by liuxilu** [comment]
好吧，怪我说的不清，是因为
https://github.com/studyzy/imewlconverter/blob/dfffb6c71255b780dd26afd0eceadb258321f22d/src/ImeWlConverterCore/IME/Win10MsPinyin.cs#L173-L182
（想来`MacPlist`也如此）
