### ISSUE TITLE
“无拼音纯汉字”模式下不管转成什么格式都提示“不好意思，发生了错误：未将对象引用设置到对象的实例”

### ISSUE THREAD

**Issue by icandura** [studyzy/imewlconverter#15]
一个大约5万多词的分行纯文本，转换成其他格式就提示“不好意思，发生了错误：未将对象引用设置到对象的实例”。
我后面分割为1000个词也还是一样，换成ANSI、UTF-8编码也一样。
不知能否修正这样的BUG

**Comment by icandura** [comment]
解决了，后面换成2.1版本就没有出现过这个问题了，之前是用新的2.1.1的版本存在这个问题。

**Comment by studyzy** [comment]
请问能否提供一下你的5W词的文件给我。我调试一下，争取以后不会再有这个问题。邮箱studyzy@gmail.com

**Comment by icandura** [comment]
不好意思，之前没太留意Github上的回复，已经给您发过去了。

**Comment by studyzy** [comment]
已经基于您的词库调试并修复了问题，您可下载最新版。
