### ISSUE TITLE
是否能增加，定时转存呢

### ISSUE THREAD

**Issue by huazhang0147** [studyzy/imewlconverter#152]
1、首先非常感谢你的软件，缺失很棒！
  2、使用中发现一些小细节，有空时，有劳优化一下。
       1）希望能自动找到微软拼音目录，自动转存，
       2）微软拼音转换微软拼音是出错

**Comment by studyzy** [comment]
微软拼音转微软拼音出错？麻烦将源词库文件发给我，我本地调试一下。
