### ISSUE TITLE
为啥我的打不开

### ISSUE THREAD

**Issue by IUswift** [studyzy/imewlconverter#156]
我下载软件后，直接点击exe还是打不开，我管理员运行也是打不开，这个为啥？

**Comment by studyzy** [comment]
难道你用的是XP？或者不是Windows

**Comment by IUswift** [comment]
我用的是windows的，版本2004，我点击exe就是弹出来一下框框就什么反应都没有了。附上GIF你看看
![Video_20201208131957](https://user-images.githubusercontent.com/75593539/101443509-8d921b00-3958-11eb-98c1-ef916c9924eb.gif)

**Comment by studyzy** [comment]
囧，你下的是源码，你要直接用下载编译好的程序就行。我放百度网盘了：链接: https://pan.baidu.com/s/13Xelxf9xzloPG1l1nA_nzQ  密码: 3uwm

**Comment by IUswift** [comment]
好的，非常感谢了

Devin <notifications@github.com> 于2020年12月8日周二 下午3:42写道：
