### ISSUE TITLE
无法转换某些uwl文件

### ISSUE THREAD

**Issue by GrandmaChen** [studyzy/imewlconverter#16]
新年快乐！

您好，我在使用此软件的时候发现有些紫光词库无法转换。是否因为文件过大？
[无法转换的词库.zip](https://github.com/studyzy/imewlconverter/files/679847/default.zip)

**Comment by studyzy** [comment]
紫光的词库比较奇葩，有些词库确实有些异常，无法解释。推荐你使用搜狗的细胞词库吧：
http://pinyin.sogou.com/dict/
