### ISSUE TITLE
20M的搜狗bin文件,转换成纯文本1分钟左右报oom异常,CPU占用20%内存占用500M

### ISSUE THREAD

**Issue by xjfuuu** [studyzy/imewlconverter#162]
弹窗报警  引发类型为“System.OutOfMemoryException”的异常。
请问这是怎么回事呢?

**Comment by hwyqb** [comment]
补充一下,搜狗版本是8.0

**Comment by studyzy** [comment]
用最新的搜狗10.0，没有发现任何问题。

**Comment by hwyqb** [comment]
截止目前还是能复现，问题无法解决，请您帮忙看下，感谢您
链接: https://pan.baidu.com/s/1Gg3ZTsGtbqlYXfLKSGZfZw  密码: w9ej

**Comment by studyzy** [comment]
[QQpinyin_from_sogou.zip](https://github.com/studyzy/imewlconverter/files/6905462/QQpinyin_from_sogou.zip)

**Comment by studyzy** [comment]
我把你的搜狗词库导入到搜狗输入法中，然后再导出，然后再用深蓝词库转换把词库文件转换为QQ拼音输入法txt格式了。一切正常。

**Comment by xjfuuu** [comment]
收到，多谢您！
