### ISSUE TITLE
双拼转换多音字问题

### ISSUE THREAD

**Issue by demo0102** [studyzy/imewlconverter#164]
目前默认的双拼转换遇到像长这样的字一股脑的转换为读音zhang，vh，忽略了chang的读音，是否可以进行方便的自定义工作？或者能否接入相关的读音查询API

**Comment by studyzy** [comment]
你说的这个不是双拼的问题，而是对词汇进行拼音生成的问题，如果原词库是没有拼音的，那么在生成目标词库的时候我会自动生成拼音，而针对多音字的情况，常见的多音字我的算法能够找到正确的读音，有些可能就注音错误了。你看看我这个例子：
![image](https://user-images.githubusercontent.com/1635408/111869228-42f15780-89b9-11eb-9ccf-b268fa7b88aa.png)

**Comment by demo0102** [comment]
> 你说的这个不是双拼的问题，而是对词汇进行拼音生成的问题，如果原词库是没有拼音的，那么在生成目标词库的时候我会自动生成拼音，而针对多音字的情况，常见的多音字我的算法能够找到正确的读音，有些可能就注音错误了。你看看我这个例子：
> ![image](https://user-images.githubusercontent.com/1635408/111869228-42f15780-89b9-11eb-9ccf-b268fa7b88aa.png)

我导入的古诗词库，错误还是很多
