### ISSUE TITLE
MAC搜狗6.0输入法导出的BIN文件无法解析

### ISSUE THREAD

**Issue by LeXwDeX** [studyzy/imewlconverter#165]
比如这种BIN文件，就无法正常解析出来。
[搜狗词库备份_2021_02_23.zip](https://github.com/studyzy/imewlconverter/files/6026552/_2021_02_23.zip)

**Comment by studyzy** [comment]
我试了一下，0条记录，看文件大小也只有400多K，看上去也好像确实没内容啊。

**Comment by zbtzbt** [comment]
我的也是mac 6.0导出的，能解析出来txt文件，但是中文乱码

**Comment by zbtzbt** [comment]
[搜狗词库备份_2021_05_10.bin.zip](https://github.com/studyzy/imewlconverter/files/6450041/_2021_05_10.bin.zip)

**Comment by zbtzbt** [comment]
更正一下，我的版本是搜狗MAC 5.10
