### ISSUE TITLE
转换时出现 Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by c14h19no2** [studyzy/imewlconverter#168]
我尝试将该帖子中（[win10自带拼音输入法词库拓展600万](https://www.52pojie.cn/thread-1227015-1-1.html)）的字库转换为Mac与Rime支持的格式，每次转换都会遇到 Exception of type 'System.OutOfMemoryException' was thrown 的问题。在这里报告一下。

**Comment by zeroppk** [comment]
同上

**Comment by studyzy** [comment]
600W确实太大了，我现在没有什么好办法。

**Comment by c14h19no2** [comment]
可以理解，确实是够大的。能否可以把软件速度降下来，限定一个最大的内存占用，让程序慢慢跑？

**Comment by c14h19no2** [comment]
可以理解，确实是够大的。我不太清楚软件的具体实现，不过还是比较好奇，能否限定一个最大的内存占用，让程序慢慢跑？

**Comment by changlianxiya** [comment]
大词库转换，可以改变处理流程。
拿拼音类词库转换为例：
先把保存文件名确定，然后逐行读取文件，(无拼音的将词转成拼音)，保存到临时目录下以拼音为文件名的文件中，可以多级目录
然后将临时文件排序后，逐个读取并处理，逐行写入目标文件。

**Comment by yfdyh000** [comment]
与 https://github.com/studyzy/imewlconverter/issues/209 相同。

更新到.NET 6并且改进代码后似乎不出错了。内存占用和速度仍有优化余地。
可体验: https://github.com/yfdyh000/imewlconverter/releases/tag/3.0-20220326
