### ISSUE TITLE
转换搜狗细胞词库失败

### ISSUE THREAD

**Issue by HRPF** [studyzy/imewlconverter#176]
转换搜狗细胞词库scel文件的时候提示”已添加了具有相同键的项“，转换失败，没有任何文件生成，请问怎么解决？

**Comment by CheongSzesuen** [comment]
同问

**Comment by cxcn** [comment]
> 同问

能否提供你转换的 scel 文件

**Comment by CheongSzesuen** [comment]
> > 同问
> 
> 能否提供你转换的 scel 文件

![image](https://user-images.githubusercontent.com/113276957/209536077-a31367e9-326d-41fb-814a-f479fee24ca7.png)


> > 同问
> 
> 能否提供你转换的 scel 文件

啊可是我转的是非常多的scel文件我把这些文件分批次转换成功了，就是有一批还是不能

**Comment by CheongSzesuen** [comment]
> > 同问
> 
> 能否提供你转换的 scel 文件

啊可是我转的是非常多的scel文件我把这些文件分批次转换成功了，就是有一批还是不能转换，还是显示“已添加了具有相同键的项”

**Comment by Shih-yenh-suan** [comment]
[威海地名.zip](https://github.com/studyzy/imewlconverter/files/12723665/default.zip)
这是出错的scel文件。

**Comment by Shih-yenh-suan** [comment]
> > 同问
> 
> 能否提供你转换的 scel 文件

[威海地名.zip](https://github.com/studyzy/imewlconverter/files/12723673/default.zip)

这是出错的scel文件。

**Comment by Shih-yenh-suan** [comment]
有可能是因为scel文件损坏了。我爬取的时候发现搜狗词库：[威海地名](https://pinyin.sogou.com/d/dict/download_cell.php?id=2775&name=%E5%A8%81%E6%B5%B7%E5%9C%B0%E5%90%8D)这个网站找不到对应页面，下载下来的词库是0kb。目前发现城市信息_山东、电子游戏、人文科学、社会科学的对应分类下有几个词典存在这种问题，删除即可
