### ISSUE TITLE
macOS下转换极点词库失败

### ISSUE THREAD

**Issue by bosconb** [studyzy/imewlconverter#180]
下载此词库的[freeime.mb](https://download.csdn.net/download/jakexxx5/4216833?utm_medium=distribute.pc_relevant_download.none-task-download-2~default~BlogCommendFromBaidu~default-6.nonecase&depth_1-utm_source=distribute.pc_relevant_download.none-task-download-2~default~BlogCommendFromBaidu~default-6.nonecase)

运行
```
dotnet ImeWlConverterCmd.dll -i:jd ./freeime.mb -o:rime ./lq.txt -ct:wubi -os:macos
```

显示内容：
```
转换开始...
11:20:51	开始生成词频...
转换完成,共转换1247个
输入 -? 可获取帮助
```

打开生成的'lq.txt'后是一堆乱码。
```
Dictionary	Freeime	1
V6.3擭{W[媁乬筽擭{蛬揯?\O?:\g譥l0		Freeime	1
12:11abcdefghijklmnopqrstuvwxyzzp11+p21+p31+p32zz<?箍蔍??%h?Y??,鏉翮	E?	ub錯g:2012-4-11	1
?廾惿%??d??C?p*3K;6O萐-`Nlms鋣D??]?尸	?徽`)?姙^??8D?X:????	1
?????蹩G?	?徽`)?姙^??8D?X:????	1
$?-?4?6揂凜????鐸螻P[抋:y虋憢?p?o?鰱!?功-???k?@?曰讣?昴????e?{?港栤???3'釨禼琸祏/~y??G?q?L?仪圃骆p?趋b?????%$+o/?2?9臕矴驩腝T+Wh_骲	??∝W??嗠^?H?宾岤鳇??e??	1
	4,	?0	?6	貱	3N	蒘	╩	蘷	鰛	D?	?	锓	缌			????T?	2?	"?	U?	=	.??????,?/?193?:?<??PE@V乑鸰j鵯媙sxV{??d?珕鐗z?E?贈????"?j?鄞杓E?涎掄??	=	1
?:?琮?
```

这种情况在转换极点mb后缀词库时发生多次，要么是几乎无实质内容，要么就是乱码。

再如[极点昱琼98词库](https://pan.baidu.com/s/1ntMKg2H)

```
dotnet ImeWlConverterCmd.dll -i:jd ./freeime.mb -o:rime ./yq.txt -ct:wubi -os:macos
```

```
转换开始...
11:28:20	开始生成词频...
转换完成,共转换3个
输入 -? 可获取帮助
```

转换结果：
```
2.1	���昱琼五笔�#���昱琼五笔	1
作者：ASun	����2011-12-27	���昱琼五笔�#���昱琼五笔	1
14:53���������zz��������������abcdefghijklmnopqrstuvwxyz�z���P@����a����工�����a����若�����aa����式�����aa����藏�����aaa����工�����aaaa�	���昱琼五笔�#���昱琼五笔	1
```

请问该如何解决？

**Comment by yfdyh000** [comment]
@bosconb 
链接1需要积分，能否上传到github或者别的网盘。
项目支持的极点五笔/郑码是纯文本格式的编码。
这些.mb的文件头是Freeime Dictionary V6.2。内容我能看到拼音和词组，但五笔字根我不了解、目前看不出对应编码关系，不知道对导出是否重要。

**Comment by yfdyh000** [comment]
已搞定。可以从 https://github.com/yfdyh000/imewlconverter/releases/tag/3.0-20220328 下载

>深蓝词库转换.exe -i:jdmb ./freeime.mb -o:rime ./lq.txt -ct:wubi
转换开始...
04:33:49        开始生成词频...
04:33:49        开始生成目标编码...
04:33:50        生成目标编码：13824/152244
04:33:53        生成目标编码：94370/152244
转换完成,共转换152244个

>深蓝词库转换.exe -i:jdmb ./attach.mb -o:rime ./lq.txt -ct:wubi
转换开始...
04:34:58        开始生成词频...
04:34:58        开始生成目标编码...
04:34:59        生成目标编码：29739/81497
转换完成,共转换81151个
