### ISSUE TITLE
有谁知道用这个把大量词组导入Mac后如何删除？

### ISSUE THREAD

**Issue by seanxushen** [studyzy/imewlconverter#187]
同步到icloud里去了，Mac上删除后过一会又出来，IOS设备只能一条条删。

**Comment by nankaims** [comment]
遇到同样的问题，难道无解吗？

**Comment by kid-oh** [comment]
https://www.jianshu.com/p/727c587f1bc6 下面的方法试试

**Comment by seanxushen** [comment]
> https://www.jianshu.com/p/727c587f1bc6 下面的方法试试

没用，Mac 上删除后就又回来，IOS删了，iCloud上还在，

**Comment by seanxushen** [comment]
> 确实没用 我已经崩溃了🤣

Macos 升级到Montery 12.x，删除了不会再回来，但是iCloud上还在。

**Comment by kid-oh** [comment]
按照知乎上的方法 把ios所有的云备份删掉 然后退出iCloud 等几分钟再登陆iCloud好像就可以了 至少我现在iPhone上只剩下msd的短语 有个新问题就是好像新加短语的话好像mac和iPhone之间不会同步了

**Comment by seanxushen** [comment]
> 按照知乎上的方法 先在mac上全选删掉 然后再把ios所有的云备份删掉 然后退出iPhone的iCloud 等几分钟再登陆iCloud好像就可以了 至少我现在iPhone上只剩下msd的短语 有个新问题就是好像新加短语的话mac和iPhone之间不会同步了

知乎？上面贴是简书吧？

**Comment by kid-oh** [comment]
> > 按照知乎上的方法 先在mac上全选删掉 然后再把ios所有的云备份删掉 然后退出iPhone的iCloud 等几分钟再登陆iCloud好像就可以了 至少我现在iPhone上只剩下msd的短语 有个新问题就是好像新加短语的话mac和iPhone之间不会同步了
> 
> 知乎？上面贴是简书吧？

后面在知乎找的方法 现在又看了一下mac和iPhone短语已经可以正常同步了 完美解决

**Comment by sunwgit** [comment]
https://github.com/studyzy/imewlconverter/issues/141#issuecomment-1080720743
