### ISSUE TITLE
百度手机输入法五笔自定义方案

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [studyzy/imewlconverter#188]
想把小小输入法的郑码码表，导入到百度手机输入法，请问可以转换吗

**Comment by wwzrh** [comment]
用多多码表编辑器V3.2的常见码表格式互转
\
\PC系统百度输入法自定义短语格式：
1,a=按
2,a=啊
1,aaj=阿
2,aaj=锕
1,dwyz=得有
1,dwyr=动物园
1,dxal=大兴安岭
\
\手机百度输入法自定义短语格式(其实是PC系统QQ输入法自定义短语格式）：
a=1,按
a=2,啊
aaj=1,阿
aaj=2,锕
dwyz=1,得有
dwyr=1,动物园
dxal=1,大兴安岭
\
深蓝词库转换imewlconverter”“用户自定义短语”有bug，没有自动生成定位（排位）码。

**Comment by nopdan** [comment]
百度输入法
