### ISSUE TITLE
搜狗细胞词库转换错误

### ISSUE THREAD

**Issue by mrz1996** [studyzy/imewlconverter#191]
linux系统下转换最新版搜狗官方网络流行新词 为自定义词库默认配置
佐佐木小次郎 zuo,zuo,mu,xiao,ci,lang
之后为乱码

**Comment by tumuyan** [comment]
我发现比较新的搜狗细胞词库文件似乎完全不能解析，旧一些的细胞词库是正常的

**Comment by yfdyh000** [comment]
2.9版exe转换正常，cmd版确实异常，不过数量够了，乱码的应该是不需要的内容。

----
> 我发现比较新的搜狗细胞词库文件似乎完全不能解析，旧一些的细胞词库是正常的

@tumuyan 有例子文件吗。

**Comment by tumuyan** [comment]
> 2.9版exe转换正常，cmd版确实异常，不过数量够了，乱码的应该是不需要的内容。
> 
> > 我发现比较新的搜狗细胞词库文件似乎完全不能解析，旧一些的细胞词库是正常的
> 
> @tumuyan 有例子文件吗。

这个更新频率很高, 我之前是没能正确解析的

https://pinyin.sogou.com/dict/detail/index/4

**Comment by yfdyh000** [comment]
> > 2.9版exe转换正常，cmd版确实异常，不过数量够了，乱码的应该是不需要的内容。
> > > 我发现比较新的搜狗细胞词库文件似乎完全不能解析，旧一些的细胞词库是正常的
> > 
> > 
> > @tumuyan 有例子文件吗。
> 
> 这个更新频率很高, 我之前是没能正确解析的
> 
> https://pinyin.sogou.com/dict/detail/index/4

但是，用 https://github.com/studyzy/imewlconverter/releases/tag/v2.9.0 解析看上去正常。

**Comment by yfdyh000** [comment]
> linux系统下转换最新版搜狗官方网络流行新词 为自定义词库默认配置 佐佐木小次郎 zuo,zuo,mu,xiao,ci,lang 之后为乱码

经研究，`SougouPinyinScel.cs` 中 `if (fs.Length == fs.Position) //判断文件结束` 改为 `if (CurrentStatus == CountWord || fs.Length == fs.Position) //判断文件结束` 可解决该问题。

----
零碎的若干修改，也不知该提交大的PR还是小的，或者发在自己的分支。= =

**Comment by tumuyan** [comment]
> 

我们有办法证明词条数量是够的嘛?我怀疑有可能文件末尾存在几个特殊词条是用新格式编码的.

不利的证据是, 搜狗细胞词库发布页的标称数量,和2.9实际转换数量不一致. 流行词库数量差1, 汽车词库差几十个.

**Comment by tumuyan** [comment]
> 经研究，`SougouPinyinScel.cs` 中 `if (fs.Length == fs.Position) //判断文件结束` 改为 `if (CurrentStatus == CountWord || fs.Length == fs.Position) //判断文件结束` 可解决该问题。

翻了一下代码，你是对的  搜狗细胞词库发布页的信息可能是维护错误了
