### ISSUE TITLE
imewlconverter只支持汉字和颜文字的词语，不支持含字母、数字、标点符号的词。

### ISSUE THREAD

**Issue by wwzrh** [studyzy/imewlconverter#202]
![屏幕截图 2021-12-04 120623](https://user-images.githubusercontent.com/12047479/144696313-967bdc3e-c4e6-4f18-a954-d7e84211592c.png)

**Comment by tumuyan** [comment]
关键的问题是，字母、数字、标点、emoji应该如何编码？
目前给出的解决方案是，字母可选直接用英语编码或者不编码，数字在字母基础上额外增加了转换为汉字进行编码的模式，标点只能选择不编码。
和emoji类似问题的还有扩展区的文字、含其他语言符号的词条。目前他们是无解的——编码无从下手。为了避免被错误编码，跳过是最好的选择

如图是我编译的版本进行的测试，pr已经合并，但是没有release新版本。测试可以看到6个词条正常编码了4个。应该是还有点问题，理论上应该可以正常编码5个词条

![image](https://user-images.githubusercontent.com/3126801/152113242-6148a05e-34ec-4888-9bdb-f2a57f2c2c4b.png)

**Comment by tumuyan** [comment]
[深蓝词库转换 (2).zip](https://github.com/studyzy/imewlconverter/files/7984699/2.zip)

覆盖了5/6的示例。另外发现原先没有考虑如何处理全角英语和数字...

![image](https://user-images.githubusercontent.com/3126801/152118523-ad8bdaac-312a-4a8d-8730-4e0760255454.png)
