### ISSUE TITLE
百度输入法的个人词库导出只能是bin

### ISSUE THREAD

**Issue by zhanggene** [studyzy/imewlconverter#204]
首先非常肯定楼主的工具很好用，最近遇到个问题，我平时使用百度输入法的批量造词功能，批量创建个人词库。然后倒入到win10的输入法中使用，最近百度的新版本（好久不更新，最近又开始更新了），导出的词库只支持bin格式。所以楼主是否可以支持百度输入法的bin格式的转换 。非常感谢
百度输入法的个人词库导出只能是bin

**Comment by miaozilong** [comment]
现在的输入法也很鸡贼，之前都是可以导出TXT的，现在不行了

**Comment by yfdyh000** [comment]
已研究但不清楚是什么编码方式。肯定没有加密或压缩算法。可能某种进制或移位。可能需要反编译大佬。

[case.zip](https://github.com/studyzy/imewlconverter/files/8354963/case.zip)  附件是测试时生成的样例文件，不熟悉hex转换的就不用下载了。万一有大佬出现呢<_<

**Comment by gary8177** [comment]
用21年版导出

**Comment by Firedoge1** [comment]
> 用21年版导出

导出不了

**Comment by Firedoge1** [comment]
https://tieba.baidu.com/p/8899815835

**Comment by Firedoge1** [comment]
现在有办法吗？

**Comment by nopdan** [comment]
> 经过分析和查找，在网上找到了编码的算法，来源是分析他们浏览器的《[某度base64魔改算法还原](https://mp.weixin.qq.com/s/Ejf5QTO2dd0LaZqnvcIKXg)》。
> 
> 文章里的分析和代码太乱了，用 Python 重写了一下，在这里贴一下解码的部分。Python 3.8 以上调用 `decode_bin()` 即可导出 UTF-16LE 的文本格式。
> 
> ```python
> MASK = 0x2D382324
> TABLE = b"qogjOuCRNkfil5p4SQ3LAmxGKZTdesvB6z_YPahMI9t80rJyHW1DEwFbc7nUVX2-"
> DECODE_TABLE = bytes.maketrans(TABLE, bytes(range(64)))
> 
> def decode(data: bytes):
>     assert len(data) % 4 == 2
>     assert (base64_remainder := data[-2] - 65) in {0, 1, 2} and data[-1] == 0
> 
>     data = data.translate(DECODE_TABLE)
>     transformed = bytearray()
> 
>     for i in range(0, len(data) - 2, 4):
>         high_bits = data[i + 3]
>         transformed += bytes((
>             data[i] | (high_bits & 0b110000) << 2,
>             data[i + 1] | (high_bits & 0b1100) << 4,
>             data[i + 2] | (high_bits & 0b11) << 6,
>         ))
> 
>     if base64_remainder:
>         for i in range(3 - base64_remainder):
>             assert transformed.pop() == 0
> 
>     result = bytearray()
> 
>     for i in range(0, len(transformed) // 4 * 4, 4):
>         chunk = MASK ^ int.from_bytes(transformed[i : i + 4], byteorder="little")
>         chunk = (chunk & 0x1FFFFFFF) << 3 | chunk >> 29
>         result += chunk.to_bytes(4, byteorder="little")
> 
>     if remainder := transformed[i + 4 :]:
>         chunk = MASK ^ int.from_bytes(remainder, byteorder="little")
>         result += chunk.to_bytes(4, byteorder="little")[: len(remainder)]
> 
>     return result
> 
> 
> def decode_bin(input_path: str, output_path: str):
>     assert input_path.endswith(".bin") and output_path.endswith(".txt")
>     with open(input_path, "rb") as f, open(output_path, "wb") as output:
>         output.write(b"\xff\xfe")
>         f.seek(1)
>         for line in f:
>             if data := line[1:-1]:
>                 output.write(decode(data))
>                 output.write(b"\n\0")
> ```

很棒，您有兴趣提 pr 吗

**Comment by Firedoge1** [comment]
非常感谢各位大佬🙏

**Comment by nopdan** [comment]
> > 很棒，您有兴趣提 pr 吗
> 
> 我没怎么写过 C# 也没有环境，对项目也不熟悉，如果你方便的话就转写一下吧。上面有别人上传的测试的文件，如果需要的话我也可以提供解码后的格式样本。
> 
> 如果可以的话麻烦在提交信息里面加上一行：
> 
> ```
> Co-authored-by: stevenlele <15964380+stevenlele@users.noreply.github.com>
> ```

我已经提交了

**Comment by nopdan** [comment]
> https://github.com/studyzy/imewlconverter/blob/3012c564f282da6fafed721cd27599397013c244/src/ImeWlConverterCore/IME/BaiduPinyinBackup.cs#L31-L32
> 
> 程序确实是按照 `<cnword>` → `<enword>` → `<sysusrword>` 的顺序导出的，应该不会出现乱序。

虽然我测试的也都是这个顺序，但也不能排除别的情况，这样写可以无视顺序。

**Comment by nopdan** [comment]
> 然后英文词的格式是：
> 
> ```
> API	0	0	4	1707932168
> ```
> 
> 分隔符是 `\t`，词频目测是 `[3]`，至于 `[1]` 和 `[2]` 的意义不明确。我这里 `[1]` 有少量的 1、2、5 等值，`[2]` 都是 0。

目前的程序对一种格式只能指定一种 CodeType，无法同时导入拼音和英文。

**Comment by qtvbwfn** [comment]
大哥，你发个版本啊。不然更新了也没办法用啊

**Comment by PandaFiredoge** [comment]
> 大哥，你发个版本啊。不然更新了也没办法用啊

https://github.com/studyzy/imewlconverter/actions/runs/8418951906

**Comment by ObravoD** [comment]
寻寻觅觅，终于被高人解决！

**Comment by ObravoD** [comment]
@nopdan 用你的包跑了下，能从pc百度输入法导出bin文件词条，但是无法导入到最新的pc搜狗输入法内。导入时，提示导入成功，但是差细胞词库，词条数为0，实际输入验证也是没导入成功。我尝试把词条缩减到几十条也没用。就差一步了，大神能再看看不。
![图片](https://github.com/studyzy/imewlconverter/assets/50982621/af812be2-bbf1-4ad6-b540-3cfd7e4dd0db)

**Comment by nopdan** [comment]
> @nopdan 用你的包跑了下，能从pc百度输入法导出bin文件词条，但是无法导入到最新的pc搜狗输入法内。导入时，提示导入成功，但是查搜狗刚导入的细胞词库，词条数为0，实际输入验证也是没导入成功。我尝试把词条缩减到几十条也没用。就差一步了，大神能再看看不。 ![图片](https://private-user-images.githubusercontent.com/50982621/340302403-af812be2-bbf1-4ad6-b540-3cfd7e4dd0db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODM2MTQsIm5iZiI6MTcxODk4MzMxNCwicGF0aCI6Ii81MDk4MjYyMS8zNDAzMDI0MDMtYWY4MTJiZTItYmJmMS00YWQ2LWI1NDAtM2NmZDdlNGRkMGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE1MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwM2Q4NjhiZTc0ZmM3YjJjMmI4NjBmYjk5MWZkN2MyNDMzMmNiODM2YWQxNzA3MTFmMjI3ZWY3ZTczNjFmN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N_qUxxy5Nb80L5C3PAK70Z5bIkbLesklyHuGd2OMsCI) ![图片](https://private-user-images.githubusercontent.com/50982621/340306658-9b16c2cc-c14c-4e53-8f3d-9cb4e5f2805c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODM2MTQsIm5iZiI6MTcxODk4MzMxNCwicGF0aCI6Ii81MDk4MjYyMS8zNDAzMDY2NTgtOWIxNmMyY2MtYzE0Yy00ZTUzLThmM2QtOWNiNGU1ZjI4MDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE1MjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhOTY4ODY4YTFjOTY3MDE0MDM1YmYyYzI0ODQ1Y2EzNmI3NDQxMzgxMzUxYmVhYzkwYzBhZDIyNmMwZjQ5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wgvTI0YvlUdvxaCAb8TH3_EHvojofCsQ6CrACwlp8bo)

搜狗新版改了格式，只需要纯汉字，不能带拼音

**Comment by zsnzzg** [comment]
> > 大哥，你发个版本啊。不然更新了也没办法用啊
> 
> https://github.com/studyzy/imewlconverter/actions/runs/8418951906

这个……咋用啊

**Comment by PandaFiredoge** [comment]
为什么没有releases？

**Comment by SandCard** [comment]
太强了,找了半天百度bin转txt,大佬这个方法是可行的

**Comment by SandCard** [comment]
> 经过分析和查找，在网上找到了编码的算法，来源是分析他们浏览器的《[某度base64魔改算法还原](https://mp.weixin.qq.com/s/Ejf5QTO2dd0LaZqnvcIKXg)》。
> 
> 文章里的分析和代码太乱了，用 Python 重写了一下，在这里贴一下解码的部分。Python 3.8 以上调用 即可导出 UTF-16LE 的文本格式。`decode_bin()`
> 
> ```python
> MASK = 0x2D382324
> TABLE = b"qogjOuCRNkfil5p4SQ3LAmxGKZTdesvB6z_YPahMI9t80rJyHW1DEwFbc7nUVX2-"
> DECODE_TABLE = bytes.maketrans(TABLE, bytes(range(64)))
> 
> def decode(data: bytes):
>     assert len(data) % 4 == 2
>     assert (base64_remainder := data[-2] - 65) in {0, 1, 2} and data[-1] == 0
> 
>     data = data.translate(DECODE_TABLE)
>     transformed = bytearray()
> 
>     for i in range(0, len(data) - 2, 4):
>         high_bits = data[i + 3]
>         transformed += bytes((
>             data[i] | (high_bits & 0b110000) << 2,
>             data[i + 1] | (high_bits & 0b1100) << 4,
>             data[i + 2] | (high_bits & 0b11) << 6,
>         ))
> 
>     if base64_remainder:
>         for i in range(3 - base64_remainder):
>             assert transformed.pop() == 0
> 
>     result = bytearray()
> 
>     for i in range(0, len(transformed) // 4 * 4, 4):
>         chunk = MASK ^ int.from_bytes(transformed[i : i + 4], byteorder="little")
>         chunk = (chunk & 0x1FFFFFFF) << 3 | chunk >> 29
>         result += chunk.to_bytes(4, byteorder="little")
> 
>     if remainder := transformed[i + 4 :]:
>         chunk = MASK ^ int.from_bytes(remainder, byteorder="little")
>         result += chunk.to_bytes(4, byteorder="little")[: len(remainder)]
> 
>     return result
> 
> 
> def decode_bin(input_path: str, output_path: str):
>     assert input_path.endswith(".bin") and output_path.endswith(".txt")
>     with open(input_path, "rb") as f, open(output_path, "wb") as output:
>         output.write(b"\xff\xfe")
>         f.seek(1)
>         for line in f:
>             if data := line[1:-1]:
>                 output.write(decode(data))
>                 output.write(b"\n\0")
> ```

太强了,网上找了半天百度bin转txt的方法,这个是可行的
