### ISSUE TITLE
2.1.2 及 2.1.3 转换成 win10 词库失败

### ISSUE THREAD

**Issue by legendtang** [studyzy/imewlconverter#21]
![image](https://cloud.githubusercontent.com/assets/1352729/24112617/17597c38-0dd5-11e7-8d9c-68b9349bd1f9.png)
如图

**Comment by studyzy** [comment]
2.1.4修复该问题。

**Comment by legendtang** [comment]
@studyzy 转换成功了，但是最后仍然会提示找不到路径 C:\temp

**Comment by studyzy** [comment]
不可能吧！我代码里面没有c:\temp这样的路径了啊！能把你的源词库，还有你的选择截图给我看看吗？studyzy@163.com

**Comment by legendtang** [comment]
很奇怪，未能重现。重现的时候会贴上的
