### ISSUE TITLE
百度拼音导出的词库是.bin格式啊，怎么转换到搜狗？

### ISSUE THREAD

**Issue by yyx3658** [studyzy/imewlconverter#221]
貌似用这个工具打不开百度词库

**Comment by cxcn** [comment]
目前还不支持。#213 #204

**Comment by joyongzhu** [comment]
> 安装旧版本软件再导出就行

请问有旧版本可以下载么？找了一圈没找到呀。

**Comment by Windows55** [comment]
2019.08.21 百度输入法 5.5.5043.0 可以导出txt

**Comment by Firedoge1** [comment]
> 2019.08.21 百度输入法 5.5.5043.0 可以导出txt

不仅没导出来，还他妈把原来的词库覆盖了

**Comment by joyongzhu** [comment]
> > 2019.08.21 百度输入法 5.5.5043.0 可以导出txt
> 
> 不仅没导出来，还他妈把原来的词库覆盖了

我已经放弃了

**Comment by gary8177** [comment]
> > > 2019.08.21 百度输入法 5.5.5043.0 可以导出txt
> > 
> > 
> > 不仅没导出来，还他妈把原来的词库覆盖了
> 
> 我已经放弃了

我成功了，去豌豆荚下载2021年的百度输入法安装同步然后导出，路径是/baidu/ime/chs.txt

**Comment by nopdan** [comment]
与 #204 重复

**Comment by Firedoge1** [comment]
> > > > 2019.08.21 百度输入法 5.5.5043.0 可以导出txt
> > > 
> > > 
> > > 不仅没导出来，还他妈把原来的词库覆盖了
> > 
> > 
> > 我已经放弃了
> 
> 我成功了，去豌豆荚下载2021年的百度输入法安装同步然后导出，路径是/baidu/ime/chs.txt

导出来的词库只有手机的，没有电脑的，同步有问题
