### ISSUE TITLE
win10系统下的微软拼音不能转换,只要一转换就说发生错误

### ISSUE THREAD

**Issue by lxk0301** [studyzy/imewlconverter#23]
把搜狗词库转换成win10系统的微软拼音词库,一直失败,

**Comment by lxk0301** [comment]
![Uploading snipaste_2017_0411_145506.png…]()
![Uploading snipaste_2017_0411_145506.png…]()

**Comment by lxk0301** [comment]
![snipaste_2017_0411_145506](https://cloud.githubusercontent.com/assets/21308593/24896344/10eb0738-1ec7-11e7-972f-f468b9b5a224.png)
这是错误提示

**Comment by studyzy** [comment]
该问题已修复，请下载最新版本。

**Comment by lxk0301** [comment]
好的    不过现在是 不支持从win10微软拼音导出的词库转换成别的输入法词库把?  比如把微软拼音转换成谷歌?
