### ISSUE TITLE
转换搜狗拼音系统词库报错

### ISSUE THREAD

**Issue by warm-ice0x00** [studyzy/imewlconverter#231]
在转换搜狗输入法 12.5.0.6558 的系统词库（[下载](https://drive.google.com/drive/folders/1R_Gs0r0hV1l_1xxQZ63cpiRQvRfkPRIO)）`sgim_core.bin`、`sgim_hz.bin` 和 `sgim_py.bin` 时，选择“搜狗拼音备份词库bin”，提示：
> 索引超出范围。必须为非负值并小于集合大小。
> 参数名: index

**Comment by cxcn** [comment]
格式不一样，需要重新分析

**Comment by studyzy** [comment]
本身不支持对系统词库的解析
