### ISSUE TITLE
win11无法使用，win11使用自定义转换成win10的dat文件导入失败

### ISSUE THREAD

**Issue by ronghc** [studyzy/imewlconverter#234]

**Comment by ronghc** [comment]
> 能否提供样例

你是指由win11导出的dat文件吗？可能我描述的不清晰，我的意思是我使用txt写了一些短语，然后按照https://blog.csdn.net/Anenan/article/details/108736118这里的方式进行转换，然后在win11系统下导入失败

**Comment by cxcn** [comment]
我希望你能下载一个[搜狗 scel 词库](https://pinyin.sogou.com/dict/detail/index/49152)，进行转换，这样可以避免你的操作失误，如果还是不行，那说明 win10 和 win11 的格式不兼容，我需要装个虚拟机进行测试。
