### ISSUE TITLE
v3.0搜狗输入法词库.bin文件转换任意格式均失败（默认设置）

### ISSUE THREAD

**Issue by Chinesered** [studyzy/imewlconverter#237]
![image](https://user-images.githubusercontent.com/120267611/224233735-14dc83d8-e7c5-42ed-a850-4dba5c03f82a.png)

**Comment by cxcn** [comment]
能否提供一下这个 bin 文件

**Comment by joyongzhu** [comment]
2.9 亲测 转换最新版本搜狗输入法导出bin词库失败。
![image](https://user-images.githubusercontent.com/17783147/225252525-7cb09094-748f-41a4-b78b-72b195262d6a.png)

**Comment by joyongzhu** [comment]
亲测，3.0版本转换也失败，搜狗输入法版本同上。
![image](https://user-images.githubusercontent.com/17783147/225254495-b30c158b-fffd-44f2-91da-484595ba5b1e.png)

**Comment by piloer** [comment]
2020年版本的搜狗拼音导出的bin文件可以转换成功  

21年和22年的没测试

**Comment by nopdan** [comment]
新的 bin 格式已经解析完了，明文储存的，比原来简单多了，搜狗终于良心发现

**Comment by nopdan** [comment]
[词库处理工具.zip](https://github.com/h4x3rotab/Sogou-User-Dict-Converter/files/11156197/default.zip)

新的工具，应该能转换了 https://github.com/imetool/dtool/commit/5528e1ebd5ae1b18cc5ab0db0f0519e96c84909a

@Chinesered @joyongzhu

**Comment by Tongzhao9417** [comment]
> [词库处理工具.zip](https://github.com/h4x3rotab/Sogou-User-Dict-Converter/files/11156197/default.zip)
> 
> 新的工具，应该能转换了 [imetool/dtool@5528e1e](https://github.com/imetool/dtool/commit/5528e1ebd5ae1b18cc5ab0db0f0519e96c84909a)
> 
> @Chinesered @joyongzhu

测试了一下，只输出了一个字，不知道为啥

**Comment by nopdan** [comment]
> > [词库处理工具.zip](https://github.com/h4x3rotab/Sogou-User-Dict-Converter/files/11156197/default.zip)
> > 新的工具，应该能转换了 [imetool/dtool@5528e1e](https://github.com/imetool/dtool/commit/5528e1ebd5ae1b18cc5ab0db0f0519e96c84909a)
> > @Chinesered @joyongzhu
> 
> 测试了一下，只输出了一个字，不知道为啥

能提供一下你的文件吗

**Comment by Tongzhao9417** [comment]
> > > [词库处理工具.zip](https://github.com/h4x3rotab/Sogou-User-Dict-Converter/files/11156197/default.zip)
> > > 新的工具，应该能转换了 [imetool/dtool@5528e1e](https://github.com/imetool/dtool/commit/5528e1ebd5ae1b18cc5ab0db0f0519e96c84909a)
> > > @Chinesered @joyongzhu
> > 
> > 
> > 测试了一下，只输出了一个字，不知道为啥
> 
> 能提供一下你的文件吗

实在不好意思，这个词库用了很多年了，里面有太多个人的隐私了，我想个办法搞一个小点文件再给您。谢谢您的付出！我先去搞一个小的可以分享的

**Comment by Tongzhao9417** [comment]
> > > [词库处理工具.zip](https://github.com/h4x3rotab/Sogou-User-Dict-Converter/files/11156197/default.zip)
> > > 新的工具，应该能转换了 [imetool/dtool@5528e1e](https://github.com/imetool/dtool/commit/5528e1ebd5ae1b18cc5ab0db0f0519e96c84909a)
> > > @Chinesered @joyongzhu
> > 
> > 
> > 测试了一下，只输出了一个字，不知道为啥
> 
> 能提供一下你的文件吗

您好，刚才我用Windows上的备份文件（400多kb）试了一下，是没有问题的。但是我Mac上的备份（4MB）放在Windows上还是失败。现在不知道是因为文件太大的缘故，还是Windows无法解析Mac的文件的缘故

**Comment by nopdan** [comment]
@Tongzhao9417  我没有 mac 没办法测试

**Comment by DonCN** [comment]
我有两个搜狗bin词库，都是报这个错误。Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

**Comment by nopdan** [comment]
@DonCN 第一个你转为纯文本格式（比如搜狗）看看。如果可以的话最好把bin发出来，有个人隐私可以私发我 me@nopdan.com

**Comment by nopdan** [comment]
用这个
[深蓝词库转换@nopdan.zip](https://github.com/studyzy/imewlconverter/files/11298485/%40nopdan.zip)

**Comment by zydchina818** [comment]
最后一个可以转换，但是词条数量不对，明显少多了。

**Comment by nopdan** [comment]
> 最后一个可以转换，但是词条数量不对，明显少多了。

发我邮箱看看
