### ISSUE TITLE
转换进度0/0

### ISSUE THREAD

**Issue by qianxindoer** [studyzy/imewlconverter#238]
![image](https://user-images.githubusercontent.com/73577848/225504908-30bd3c4f-c466-4f64-9998-6bf50ec08d1e.png)
3.0版本150k的搜狗备份文件不能转换为Gboard小鹤双拼词库，进度为0/0

**Comment by nopdan** [comment]
[词库处理工具.zip](https://github.com/h4x3rotab/Sogou-User-Dict-Converter/files/11156197/default.zip)

新的工具，应该能转换了 https://github.com/imetool/dtool/commit/5528e1ebd5ae1b18cc5ab0db0f0519e96c84909a

@qianxindoer @scientificworld

**Comment by scientificworld** [comment]
> [词库处理工具.zip](https://github.com/h4x3rotab/Sogou-User-Dict-Converter/files/11156197/default.zip)
> 
> 新的工具，应该能转换了 [imetool/dtool@5528e1e](https://github.com/imetool/dtool/commit/5528e1ebd5ae1b18cc5ab0db0f0519e96c84909a)
> 
> @qianxindoer @scientificworld

可以转换，感谢大佬。另外能不能导出为带词频的 RIME 格式？谢谢。

**Comment by nopdan** [comment]
> 

等 #241 合并，词组少的问题我也注意到了，但是导出的文件里确实只有那么多信息。你可以用 hex 编辑器看一下 0x40 开始的 4 个字节，这是词组数。

**Comment by qianxindoer** [comment]
谢谢大佬，不过现在点击转换并保存之后虽然提示已转换，但是保存的文件是一个0字节的空白文件[image: image.png]

单单 ***@***.***> 于2023年4月5日周三 15:25写道：

**Comment by nopdan** [comment]
@scientificworld @qianxindoer 用这个
[深蓝词库转换@nopdan.zip](https://github.com/studyzy/imewlconverter/files/11298469/%40nopdan.zip)

**Comment by akira304moto** [comment]
> @scientificworld @qianxindoer 用这个
> [深蓝词库转换@nopdan.zip](https://github.com/studyzy/imewlconverter/files/11298469/%40nopdan.zip)

大佬，保存出来的txt是gb2312编码的，“㗎”这类字会直接成为“?”，可否直接用UTF-8保存呢？谢谢！

**Comment by Ciaoye** [comment]
> @scientificworld @qianxindoer 用这个 [深蓝词库转换@nopdan.zip](https://github.com/studyzy/imewlconverter/files/11298469/%40nopdan.zip)

这个没有问题，感谢！

**Comment by hdw9703** [comment]
> > @scientificworld @qianxindoer 用这个 [深蓝词库转换@nopdan.zip](https://github.com/studyzy/imewlconverter/files/11298469/%40nopdan.zip)
> 
> 这个没有问题，感谢！

![image](https://github.com/studyzy/imewlconverter/assets/35803751/24948ce9-b426-4ea0-9601-e9887b35968a)
用这个提示没有找到词条

**Comment by Bluecat003** [comment]
> ![image](https://user-images.githubusercontent.com/73577848/225504908-30bd3c4f-c466-4f64-9998-6bf50ec08d1e.png) 3.0版本150k的搜狗备份文件不能转换为Gboard小鹤双拼词库，进度为0/0

这个问题已经解决了吗，如果辉滚到旧版本，词库内容会不会少呢
