### ISSUE TITLE
关于算法溢出

### ISSUE THREAD

**Issue by wangjunqi** [studyzy/imewlconverter#24]
你好。我在使用Win10系统。下载的是2.2版本的转化器。从搜狗的bin文件转换到微软win10拼音输入法的词库时，出现了算术运算导致溢出的错误。请问应该如何解决？

**Comment by studyzy** [comment]
你好，搜狗的bin词库被加密，已经不支持了。你可以下载7.2版之前的搜狗拼音，然后导出词库。
