### ISSUE TITLE
绝了，没有一个能转换的

### ISSUE THREAD

**Issue by kiradzS** [studyzy/imewlconverter#253]
搜狗bin：Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
QQ输入法ini：转换失败，没有找到词条
搜狗拼音txt：转换失败，没有找到词条
总共就用过三种一个都没法用，浪费一小时折腾，这是啥恶做剧项目吗

**Comment by nopdan** [comment]
https://github.com/nopdan/imewlconverter/releases
