### ISSUE TITLE
搜狗个人词库转换成gboard失败

### ISSUE THREAD

**Issue by leosj** [studyzy/imewlconverter#255]
dotnet ImeWlConverterCmd.dll -i:sgpybin ./source.bin -o:gboard ./gboard.txt 
转换开始...
16:31:49	词库（source.bin）处理出现异常：
	Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
转换完成,共转换0个
输入 -? 可获取帮助

**Comment by 46fafa** [comment]
我也遇到类似问题，我点击转换之后没有反应

**Comment by CleMooling** [comment]
+1

**Comment by nopdan** [comment]
@leosj @46fafa @CleMooling 用我 fork 的
