### ISSUE TITLE
多个词库合并的时候，提示已添加了具有相同项的键

### ISSUE THREAD

**Issue by printff** [studyzy/imewlconverter#26]
重复的可能直接忽略吧？
我导入多个词库，难免有些词是重复的

**Comment by studyzy** [comment]
你好，经过测试，没有发现你说的这个异常。我在程序中对多词库是进行了去重的。能否把你的源词库发给我，并告之你的目标词库是什么。我本地调试一下。studyzy[a]163.com

**Comment by printff** [comment]
不好意思，我是用脚本批量下载搜狗词库的，结果有些下载失败，文件大小变成0了，输入大小为0的时候就会有这个错误
