### ISSUE TITLE
谁能把微信输入法电脑版的词库提取出来？

### ISSUE THREAD

**Issue by i990049** [studyzy/imewlconverter#260]
张小龙开发的，之前叫微信键盘，电脑版手机版都有，这个输入法自带词库和只能联想还是挺全的，目前不能导入导出词库，哪位懂的帮忙提取转换一下词库?

**Comment by studyzy** [comment]
等待官方版本更新，官方出了用户词库导入导出就好了。

**Comment by qqlcx5** [comment]
> 等待官方版本更新，官方出了用户词库导入导出就好了。

半年了，你知道我这半年怎么过的？
