### ISSUE TITLE
遇到了搜狗bin词库转换失败的问题index out of range

### ISSUE THREAD

**Issue by Pger-Y** [studyzy/imewlconverter#261]
<img width="637" alt="image" src="https://github.com/studyzy/imewlconverter/assets/4125972/8727b23b-baed-4e90-bca1-556fe866e2a7">
index was out of range，不确定是哪里导出有问题还是说搜狗这破公司又改格式了，bin文件大概6MB大小，然后转换过程中大概消耗了1G内存之后就报这个错退出了，辛苦有时间看下这个问题:)

**Comment by 46fafa** [comment]
> 试试降低版本,我用最新的v13版本会这样,重装了v11.6.0版本的搜狗输入法成功了

老哥，能分享一下老版本的搜狗法吗

**Comment by 46fafa** [comment]
> <img alt="image" width="637" src="https://user-images.githubusercontent.com/4125972/256979865-8727b23b-baed-4e90-bca1-556fe866e2a7.png"> index was out of range，不确定是哪里导出有问题还是说搜狗这破公司又改格式了，bin文件大概6MB大小，然后转换过程中大概消耗了1G内存之后就报这个错退出了，辛苦有时间看下这个问题:)
没找到旧版本的搜狗输入法，我用爬虫爬了搜狗主要词库然后转换

**Comment by nopdan** [comment]
@Pger-Y @imRoxy2222 @46fafa  为什么你们就是不愿翻一下issue呢 #237 #238 #250
