### ISSUE TITLE
This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.-此BackgroundWorker 当前正忙，无法同时运行多个任务。

### ISSUE THREAD

**Issue by xiqian2** [studyzy/imewlconverter#264]
提示”This BackgroundWorker is currently busy and cannot run multiple tasks concurrently.“，怎么解决
系统及其他信息：
Windows 11 家庭中文版
22H2
net 4.6已安装
已管理员运行
![image](https://github.com/studyzy/imewlconverter/assets/117052180/6763c2c4-8da3-4b33-9fbf-e70c456ff0cc)

**Comment by HaseozZ** [comment]
加一

**Comment by 1204244136** [comment]
疑似内存泄漏

**Comment by nopdan** [comment]
搜狗备份格式更新了，提了 pr 没人看，可以先用这个 https://github.com/nopdan/rose

**Comment by nopdan** [comment]
https://github.com/nopdan/imewlconverter/releases

**Comment by xiqian2** [comment]
> 搜狗备份格式更新了，提了没人看，可以先用这个https://github.com/nopdan/rose

感谢
