### ISSUE TITLE
添加 Fcitx 输入法的 libime 二进制词库支持

### ISSUE THREAD

**Issue by cxplay** [studyzy/imewlconverter#269]
Fcitx 导入后生成的是 libime 二进制词库.

> 关于 Fcitx 的词库: https://fcitx5-android.github.io/faq/#_10

- https://github.com/fcitx/libime/blob/master/tools/libime_pinyindict.cpp

**Comment by LakeishaKowalczyk** [comment]
+1

**Comment by nopdan** [comment]
fcitx 官方已经提供了工具
