### ISSUE TITLE
林格斯词库不能正确提取

### ISSUE THREAD

**Issue by gzliudan** [studyzy/imewlconverter#27]
只需要提取词汇本身就行，不需要编码、词频、释义，但保存后文件大小是0。
http://www.lingoes.cn/zh/dictionary/dict_cata.php?cata=4.e&lang=&order=0

**Comment by studyzy** [comment]
是的，有些灵格斯的词库我可以转换，有些会失败，我也不知道什么原因，你需要哪个具体的词库，告诉我，我试一试本地调试着给你转换吧。

**Comment by gzliudan** [comment]
本草纲目、汉英中医大词典、汉英医学大词典、汉英药名词典、湘雅医学专业词典、英中医学辞海

**Comment by studyzy** [comment]
你试一下把高级设置中的词条过滤设置改成不过滤，然后把目标词库选无拼音纯汉字。这样可以导出。

**Comment by gzliudan** [comment]
还是不行，转换后大小变成1KB，之前是0。我把词典发到你163邮箱里，麻烦你再测试一下。如果能行，就发回结果给我。

**Comment by studyzy** [comment]
已经把转换结果发送到你邮箱。

**Comment by gzliudan** [comment]
词汇编码要选Unicode，之前我选的是UTF8。非常感谢作者的热心支持。
