### ISSUE TITLE
搜狗scel转搜狗txt失败

### ISSUE THREAD

**Issue by kidzgy** [studyzy/imewlconverter#275]
![微信截图_20231016153450](https://github.com/studyzy/imewlconverter/assets/6967810/198627ec-debb-473d-a355-b9a6bdf54602)
测试环境：搜狗8.9C、深蓝3.0

测试步骤：
1、先用深蓝将 https://github.com/iDvel/rime-ice/blob/main/cn_dicts/base.dict.yaml 这个词库，rime转为搜狗txt。
2、在搜狗设置界面导入txt词库，导入成功后，在C:\Users\Administrator\AppData\LocalLow\SogouPY\scd 生成对应的scel细胞词库
3、将该细胞词库重新转为txt——失败

**Comment by nopdan** [comment]
能否提供转换之后的 scel 文件

**Comment by kidzgy** [comment]
> 能否提供转换之后的 scel 文件

[成语俗语歇后语.zip](https://github.com/studyzy/imewlconverter/files/14062473/default.zip)

**Comment by nopdan** [comment]
已解决，可以在 https://github.com/studyzy/imewlconverter/actions/runs/7666327981 下载自动编译的程序
