### ISSUE TITLE
.NET6 不上不下的，希望考虑兼容性

### ISSUE THREAD

**Issue by lenny20** [studyzy/imewlconverter#282]
最好兼顾老用户，兼容NET4.8吧，否则只能用旧版深蓝导出TXT，再用多多转码。深蓝的自定义转码一直不好用。
.NET8 LTS 正式发布了，真不想装6。不过，转换编码格式真需要这么高的版本么？

**Comment by yfdyh000** [comment]
之前没有.NET 8，且6是LTS，总会有一些程序用到吧。
不太记得放弃framework 4.8的原因，可能出于调试和性能，以及.net framework停更和不够跨平台（当时理解）。

https://learn.microsoft.com/zh-cn/dotnet/core/versions/selection#control-roll-forward-behavior  `--roll-forward LatestMajor` 不知道行不行。

**Comment by lenny20** [comment]
“调试和性能”，调试好了可以用NET4.8编译吧？现在的硬件速度够快了，而且深蓝限制了2万行，谈速度就没啥意义了。
