### ISSUE TITLE
希望取消2万行限制！

### ISSUE THREAD

**Issue by lenny20** [studyzy/imewlconverter#285]
微软拼音限制导入词条2万条，那就为这种格式做特别提示，不该把这种限制应用到所有输入法啊！
要把几十万词库拆分为每次2万条，很烦人的！
微软拼音很多人用，但很少人为其添加词库。

**Comment by studyzy** [comment]
是为微软拼音做的特别限制啊。如果你导出成其他输入法，不会限制 2 万条的。
