### ISSUE TITLE
请问下载了如何打开

### ISSUE THREAD

**Issue by horasan106** [studyzy/imewlconverter#288]
里面没有.exe文件，如何运行软件？

**Comment by yfdyh000** [comment]
你下载的是[imewlconverter-v3.0.0-windows.zip](https://github.com/studyzy/imewlconverter/releases/download/v3.0.0/imewlconverter-v3.0.0-windows.zip)吗

**Comment by horasan106** [comment]
我下载的是[[studyzy](https://github.com/studyzy)
/
[imewlconverter](https://github.com/studyzy/imewlconverter)](https://github.com/studyzy/imewlconverter)
是不是下载错了

**Comment by yfdyh000** [comment]
https://github.com/studyzy/imewlconverter/releases 的 -windows.zip

**Comment by horasan106** [comment]
谢谢
