### ISSUE TITLE
win10微软拼音自学习词汇

### ISSUE THREAD

**Issue by skyairun** [studyzy/imewlconverter#291]
不知道是不是编码改了，win10导出的自学习词汇，没办法转换，提示没有找到词条。

**Comment by nopdan** [comment]
无法复现，你是不是选错格式了。`Win10微软拼音（自学习词库）`

**Comment by skyairun** [comment]
win10家庭中文版22H2
1.在“词库与自学习”—“自学习”—“导出自学习词汇”，自动生成“ChsPinyinUDL.dat”文件。
2.此文件用深蓝词库打开，可能因为后缀一样，默认识别为“Win10微软拼音（自定义短语）”，无论是用默认，还是手动选成“自学习词库”，都不能转换成其他格式。

3.反向操作的话，可以讲其他格式转成“自学习词库”。但即便“导入自学习词汇“显示成功，实际测试仍然没有生效。

**Comment by jocemod** [comment]
win10专业工作站版22H2
![image](https://github.com/user-attachments/assets/094a6258-6064-4de8-b6d3-fcba4472c1a6)

**Comment by nopdan** [comment]
fixed in 67b0e61
