### ISSUE TITLE
3.0.0 生成的微软自学习词库无法导入

### ISSUE THREAD

**Issue by Wenti-D** [studyzy/imewlconverter#292]
我尝试把我的搜狗用户词库转换为微软拼音自学习词库，但是 3.0.0 版本出来的转换结果在 Win 11 22H2 导入失败，提示「文件已损坏或格式不正确」，然而 2.9.0 生成的结果却可以。

**Comment by Xinli-GUMP** [comment]
3.1版本依然存在该bug，通过搜狗bin词库转换成微软自学习无法导入

**Comment by hu-chu** [comment]
3.1依旧存在bug

**Comment by laozhoubuluo** [comment]
3.1确认可复现此问题

**Comment by nopdan** [comment]
fixed in 67b0e61

**Comment by lloydgyt** [comment]
3.2版本也出现这个问题
