### ISSUE TITLE
请问有人解析过搜狗自带的词库吗？其他资料都是使用细胞词库

### ISSUE THREAD

**Issue by plutotree** [studyzy/imewlconverter#293]
搜狗的[细胞词库](https://pinyin.sogou.com/dict/)词库由用户上传，其实质量一般，而且绝大多数都不会更新。下载了全量细胞词库，上百万的词条其实很多都是浪费的，这辈子都用不上哈。
我比较需要的是搜狗输入法自带的词库，这块应该会跟着搜狗的版本更新而更新，并且都是精选的词汇。在安装目录里面找了下，感觉这些文件应该是，但是不知道具体是哪个文件，使用工具很多解析是出错的。

不知道有没有人有研究过搜狗自带词库，多谢了

<img width="296" alt="image" src="https://github.com/studyzy/imewlconverter/assets/60023/36952a64-b25d-4686-bda2-5457130e5927">

**Comment by lenny20** [comment]
肯定有啦，只是怕被告不敢发出来而已。

**Comment by plutotree** [comment]
> 肯定有啦，只是怕被告不敢发出来而已。

说的是你自己么 哈？话说文件格式解析并不构成侵权吧
