### ISSUE TITLE
转换出来的 Win10 微软拼音词库默认位置是 1

### ISSUE THREAD

**Issue by AkazaDorian** [studyzy/imewlconverter#30]
这样的话自定义的词库总是排在第一个，但是我比较想要放在第九个（最后一个），不知道有没有办法解决呢？谢谢！

**Comment by hhggit** [comment]
@studyzy 这个功能是可以做的。 *candidate2*（候选框位置）这个字段的第一个字节就是就是位置。第二个字节可能是位置的权重。做[mschxudp](https://github.com/hhggit/mschxudp) 这个导出脚本时候就做了导出位置 **,排序位置**。

另外这个格式可以支持五笔。




```
#                                                      candidate2
#           phrase_offsets[]         magic_X     phrase_offset2
# 00000040  00 00 00 00 24 00 00 00  10 00 10 00 18 00 05 06  |....$...........|
#           phrase_unknown8_X        pinyin

**Comment by studyzy** [comment]
已修复，并发布新版本2.2.2，可以在高级设置中修改词频
