### ISSUE TITLE
Rime userdb.txt用户词典格式异常

### ISSUE THREAD

**Issue by Lion176** [studyzy/imewlconverter#306]
Rime userdb.txt的拼音输入法格式是先拼音后字词，但是通过程序导出的格式是先字词后拼音。

Rime userdb.txt需要的格式：
a 	啊	c=50 d=6.98904 t=23600
a li yun 	阿里云	c=4 d=1.01386 t=23600
a li yun pan 	阿里云盘	c=1 d=0.00960953 t=23600
a mu 	阿木	c=1 d=0.0702988 t=23600
ai hao 	爱好	c=1 d=0.112478 t=23600
ai ta mei 	爱他美	c=1 d=0.0119742 t=23600
an 	按	c=34 d=4.45143 t=23600

通过程序实际导出的Rime userdb.txt格式：
啊哈	a ha	1
阿拉伯联合酋长国	a la bo lian he qiu zhang guo	1
阿里巴巴	a li ba ba	1
阿里巴巴国际站	a li ba ba guo ji zhan	1
阿里妈妈	a li ma ma	1
阿里旺旺	a li wang wang	1

**Comment by nopdan** [comment]
词库信息不足，本不应该支持导出 Rime userdb 格式的，我会删掉。
你可以导出普通的 rime 词库使用。
