### ISSUE TITLE
搜狗备份词库转换失败，数组索引越界

### ISSUE THREAD

**Issue by IM-Boting** [studyzy/imewlconverter#308]
![image](https://github.com/studyzy/imewlconverter/assets/47098029/ce9514f5-142c-4132-b7ad-f65c112efc85)

深蓝3.1最新源码编译，经过调试发现下图红框位置索引值为-2，导致异常
![image](https://github.com/studyzy/imewlconverter/assets/47098029/d105c34a-f320-4425-b6da-39e3e3e1c2bb)

搜狗输入法为14.3.0正式版

**Comment by nopdan** [comment]
这是搜狗自带的词库，不是你手动导出的备份词库

**Comment by IM-Boting** [comment]
哦明白了，备份词库使用搜狗导出的是吧。那这种自带的词库该如何解析？我只看得到英文词汇

**Comment by nopdan** [comment]
> 哦明白了，备份词库使用搜狗导出的是吧。那这种自带的词库该如何解析？我只看得到英文词汇

自带的词库每个都是不同的格式，没有通用解法
