### ISSUE TITLE
转化后的词频全为1

### ISSUE THREAD

**Issue by jk123vip** [studyzy/imewlconverter#31]
版本：2.2.1.0
转化词库（.scel）为txt文件，选择自定义方式，输出txt文件格式正确，但所有词的词频全都是1，请问下是什么原因？有办法解决吗？谢谢了！

**Comment by studyzy** [comment]
因为.scel里面并没有词频啊。

**Comment by studyzy** [comment]
可以选择高级设置里面的词频生成设置
