### ISSUE TITLE
果然win10微软拼音自定义短语对双拼还是不友好

### ISSUE THREAD

**Issue by daiaji** [studyzy/imewlconverter#32]
![default](https://user-images.githubusercontent.com/25875791/29931759-b9e236fc-8ea4-11e7-83a5-853f9b3e93d5.png)
虽然一开始得知这个消息就觉得很不祥
自定义短语啥时候这么好用啦？
用的时候才发现根本没有平常用的词
看了一下短语
好嘛 这是只有在用全拼时才会触发的啊……
只能说等哪天各位大佬解析出了dat的结构了

**Comment by studyzy** [comment]
输入法不支持我也是没办法啊。

**Comment by daiaji** [comment]
@studyzy 指不定哪天会改回来……
要不就是微软会不会有SDK
没有那就只能看没有好心的hacker了
