### ISSUE TITLE
请求支持Fcitx5 (Linux / Android)输入法词库格式

### ISSUE THREAD

**Issue by NJYZ-96** [studyzy/imewlconverter#321]
Fcitx5输入法项目地址：
[Fcitx5 ( Android)](https://github.com/fcitx5-android/fcitx5-android)
[Fcitx5 (Linux )](https://github.com/fcitx/fcitx5)

这里提供一份该输入法的第三方词库文件，供参考：[文件下载地址](https://github.com/wuhgit/CustomPinyinDictionary/releases/download/assets/CustomPinyinDictionary_Fcitx_20240621.tar.gz)
第三方词库地址：https://github.com/wuhgit/CustomPinyinDictionary?tab=readme-ov-file

**Comment by NJYZ-96** [comment]
补充说明：我的需求是将Fcitx5词库转换为TXT或者其他第三方，原因是上面的第三方词库作者只提供Fcitx5词库；虽然该作者提供转换TXT的方法，但由于我没有Linux 系统使用能力，难以实现，所以问问这边有没有可能支持；

由于这个需求过于小众，不支持的话就帮我关闭吧，打扰了

**Comment by devome** [comment]
以Arch Linux为例，需要安装 [libime@Extra](https://archlinux.org/packages/extra/x86_64/libime/) 和 [imewlconverter@AUR](https://aur.archlinux.org/packages/imewlconverter)

```shell
libime_tabledict -d -u CustomPinyinDictionary_Fcitx.dict temp.txt
imewlconverter -i:libpy temp.txt -o:<输出格式> <输出文件>
```

**Comment by NJYZ-96** [comment]
> 安装一个WSL其实也不难的，WSL中就可以使用转换命令了：
> 
> ```shell
> libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict CustomPinyinDictionary_Fcitx.txt
> ```
> 
> 我这里就帮你转换一下吧：[CustomPinyinDictionary_Fcitx.zip](https://github.com/user-attachments/files/16371480/CustomPinyinDictionary_Fcitx.zip)

太感谢你了，愿你事事如意
