### ISSUE TITLE
词库经常推荐一些露骨黄色的词句

### ISSUE THREAD

**Issue by qqlcx5** [studyzy/imewlconverter#327]
巨无语，强烈推荐官方对这些词库进行屏蔽。 难道是微信很多人来开车被收录过来？

第二个问题，就是管理很多设备后，词库无法删除，比如我在手机端清空词库，结果转眼又被其他端更新到。我希望PC等设备也能同步清空。有洁癖，因为有时候输错词，结果这个词在各各端都有。

第三个问题，macOS 10.15系统 16寸英特尔电脑上，这个输入法一段时间程序会崩溃，需要重新安装。。

**Comment by studyzy** [comment]
本工具不生产词库，只是词库的搬运工。😂😂😂
