### ISSUE TITLE
❗搜狗细胞词库转换失败：Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Gloryandel** [studyzy/imewlconverter#336]
![image](https://github.com/user-attachments/assets/93dadd20-2b47-46d9-9d17-82823f60642a)

**Comment by Gloryandel** [comment]
Windows11 24h2 Microsoft Windows Desktop Runtime - 6.0.29 (x64) 和 Microsoft Windows Desktop Runtime - 8.0.10 (x64)

**Comment by nopdan** [comment]
fixed in 9ce6aae
