### ISSUE TITLE
微软双拼的.dat文件无法导出，一直提示0词条

### ISSUE THREAD

**Issue by ChloemoShaw** [studyzy/imewlconverter#34]
用了2.2.1和2.2.2，都是这个现象。
我使用的时候，不间断地导出词库的.dat文件是不断增大的，但是无论是那个时间的词库文件都是同样的提示，0词条。 @studyzy

**Comment by studyzy** [comment]
我好想没有支持微软双拼这个输入法。你怎么选择的，源词库文件是什么，发给我看看。

**Comment by ChloemoShaw** [comment]
也就是，你们在页面上说的Win10微软拼音（1703版dat格式），win1o微软双拼，{到出自学习词汇]，里面的词库，得到.dat文件。

**Comment by studyzy** [comment]
不好意思，不支持自学习词汇，没办法解析。

**Comment by ChloemoShaw** [comment]
Win10微软拼音（1703版dat格式）中的。dat格式是指什么？是指自定义短语么？

**Comment by studyzy** [comment]
是的。自定义短语。
