### ISSUE TITLE
“不好意思，发生了错误：未将对象引用设置到对象实例”

### ISSUE THREAD

**Issue by liyi3344520** [studyzy/imewlconverter#35]
我是Windows10系统，对搜狗词库 转换。
安装后可以转换，但是第三次转换开始，就出现“不好意思，发生了错误：未将对象引用设置到对象实例”。

我重新试了，原先能转换的词库，现在不能转换了。

我用的是Release_V2.2.1.zip版本。

**Comment by studyzy** [comment]
能否将你的词库文件发给我，我本地调试一下。

**Comment by studyzy** [comment]
搜狗词库最新版已解决
