### ISSUE TITLE
使用  简繁 转换 组件选择 office 时提示： 对象以被删除  使用 office 组件 需要  office 版本是多少？

### ISSUE THREAD

**Issue by q158073378252010** [studyzy/imewlconverter#36]
使用  简繁 转换 组件选择 office 时提示： 对象以被删除  使用 office 组件 需要  office 版本是多少？

相同的词库，如果 使用系统默认组件则可完成！
希望能解释下！

**Comment by studyzy** [comment]
你好。我使用的是Office 12.0，也就是Office 2007的库。使用系统默认组件会好些，速度快。
