### ISSUE TITLE
win10转换词库提示：不好意思，发生了错误，给定关键字不在字典中

### ISSUE THREAD

**Issue by feileb** [studyzy/imewlconverter#37]
使用命令行可以转换rime词库，但是转换出来的是拼音词库，帮助里面也没有写如何转换为五笔词库

`深蓝词库转换.exe -i:qqwb QQ五笔系统词库.txt -o:rime rime.txt`

**Comment by feileb** [comment]
测试2.1.0.0版本转换是正常的，后面的版本不能转换rime的五笔词库

**Comment by studyzy** [comment]
能否提供一下你的詞庫文件，然后目标词库你选的什么，我本地调试一下。

**Comment by xjushi** [comment]
同样的问题，最新版，QQ五笔的无法转换到Rime

**Comment by studyzy** [comment]
对于有问题的词库。麻烦将词库文件发给我。我本地调试一下。谢谢。

**Comment by studyzy** [comment]
我需要的是二进制文件，是一个文件，不是内容。你把文件发我邮箱吧。

**Comment by studyzy** [comment]
Add -ct:wubi  -os:linux to command line.
