### ISSUE TITLE
大神，能不能加个txt转五笔scel细胞词库

### ISSUE THREAD

**Issue by ulpyuxa** [studyzy/imewlconverter#38]
大神，能不能加个txt转五笔scel细胞词库，
最近用搜狗五笔，自己做了几十万的五笔词库txt文件，但在网上只能scel转txt的，官方上传转换只能是50000个一个文件，所以想大神能不能加个直接转scel的功能。

**Comment by studyzy** [comment]
你好，不支持，从scel能够转txt并不意味着我能够解析scel格式的每个字节的意思。实际上很多字节我并不知道是什么意思，只是因为没有用到，所以跳过了。所以在没有完整的scel内部格式的说明的情况下，无法生成scel文件。
