### ISSUE TITLE
Win10微软拼音不支持双拼

### ISSUE THREAD

**Issue by thelastfantasy** [studyzy/imewlconverter#42]
导出来的全是全拼，双拼用户完全没法用...

再喷一下微软拼音：
我把10000多条词库导入到自定义短语直接导致微软拼音设置窗口卡死了，说明使用自定义短语来导入词库这个做法本身就有点不合适，
真正适合的导入方式应该是微软的专业词库功能，然而微软又没有提供相应接口...

**Comment by viazure** [comment]
双拼这个东西我找到一个小工具可以加，但是只有自然码。先提取汉字，然后在注音里加上自然码双拼。
[CiKuTool.zip](https://github.com/studyzy/imewlconverter/files/1987818/CiKuTool.zip)

**Comment by studyzy** [comment]
最新版已支持。只要源是双拼，那么导出的Win10微软拼音就是双拼。
