### ISSUE TITLE
win10 1709导入.dat 词库提示格式损坏。

### ISSUE THREAD

**Issue by xuefengliang** [studyzy/imewlconverter#43]
转换的.dat 词库在win10 1703上没有问题，在win10 1709上提示格式损坏。

**Comment by lightmotion** [comment]
同1709导入不能，/(ㄒoㄒ)/~~

**Comment by tonyhsu** [comment]
V2.2.1，win10 1709，导出文件是1703，提示格式损坏

**Comment by tonyhsu** [comment]
导入的位置错了，在#40，@studyzy 兄指出了原因，是自定义短语，而不是自学习词汇。
