### ISSUE TITLE
win10 1803 导入转换后的词库后，显示文件损坏或错误

### ISSUE THREAD

**Issue by fan3271** [studyzy/imewlconverter#45]
如题。
好像咱们新版本只支持到1703，1803还是不行。
不过还是要感谢一下，给人以希望！

**Comment by fan3271** [comment]
是我的问题，我导入到学习那里了，应该是“用户自定义短语”，成功了！谢谢s大
不过，似乎它把词频搞成了位置
![image](https://user-images.githubusercontent.com/38968497/39700602-586baa98-5230-11e8-9bb7-9a013f9f6bdb.png)
有些常用的话反而在很后面很后面的位置了

**Comment by studyzy** [comment]
恩，你可以先导出成其他不带词频的格式，然后把新格式再导入变成微软拼音即可。

**Comment by fan3271** [comment]
回来还愿了！谢谢大神回复，按你的方法，现在完美！
另外想问一下，是不是GITHUB可以通过邮件来实现回复？

**Comment by studyzy** [comment]
我现在就是在Gmail里面回复GitHub的。

2018-05-08 10:54 GMT+08:00 fan3271 <notifications@github.com>:
