### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by wheesys** [studyzy/imewlconverter#49]
2.2版本--细胞词库转微软拼音词库时,微软拼音词库占地太大,极易内存溢出,能否增加内存占用设置,或使用类似winrar的临时文件?

**Comment by wheesys** [comment]
转换软件溢出，以我的经验来看，应该是你软件设定的进程内存相关的。2018年8月12日 22:19，Devin <notifications@github.com>写道：到底是微软拼音内存溢出了还是我这个转换软件内存溢出了，导致无法产生词库文件？

**Comment by Clear-up** [comment]
2.4.1 搜狗.bin转win10拼音，内存溢出转换失败了（System.OutOfMemoryException），我一直盯着任务管理器，程序内存占用最大也就1G多点，机子内存总共占用才50%，不存在超内存的情况。我搜狗词库.bin有20M，不知道是不是太大了，请问这个能解决吗？
