### ISSUE TITLE
不好意思，发生了错误；算数运算导致溢出。

### ISSUE THREAD

**Issue by Northyluvhkbad** [studyzy/imewlconverter#52]
这是因为我的词库文件太大了吗？？
搜狗导出来的bin，才不到4M

**Comment by MEZboy** [comment]
同样，我15M的词库也是该提示，从搜狗转换为Win10微软拼音的提示

**Comment by tmxkn1** [comment]
[**@MEZboy**](https://github.com/MEZboy) commented on [Sep 6, 2018, 8:47 AM GMT+1](https://github.com/studyzy/imewlconverter/issues/52#issuecomment-418998462 "2018-09-06T07:47:22Z - Replied by Github Reply Comments"):
> 同样，我15M的词库也是该提示，从搜狗转换为Win10微软拼音的提示

一樣哦 期待修復~

**Comment by studyzy** [comment]
最新版搜狗bin词库已经可以转了。

**Comment by loveJasmine** [comment]
最新版的sogou bin文件又不行了
