### ISSUE TITLE
帮忙测试一下华宇紫光词库.uwl是不是词条数大的问题(50万)？

### ISSUE THREAD

**Issue by zgdlime** [studyzy/imewlconverter#53]
@studyzy 帮忙测试一下华宇紫光词库.uwl是不是词条数大的问题(50万)？

一：以下词库转换成功，该词词条数小于50万。
华宇系统词库,词条数： 426086条 
http://www.unispim.com/php/download.php?wordlib=8

二：以下词库转换不成功，该词词条数大于50万。
华宇大词库完美优化第六版,词条数： 574452条 
http://www.unispim.com/php/download.php?wordlib=40
紫光词库10.8，词条数： 833932条 
http://www.unispim.com/php/download.php?wordlib=66

**Comment by studyzy** [comment]
[紫光词库完美优化第六版.zip](https://github.com/studyzy/imewlconverter/files/2525680/default.zip)
[sys.uwl.zip](https://github.com/studyzy/imewlconverter/files/2525681/sys.uwl.zip)

**Comment by studyzy** [comment]
我已经将你要的两个文件转换好了。你直接使用吧。紫光的编码格式不统一，在哪个字段定义编码格式我不清楚，所以试了很多种格式，试出来正确的。
