### ISSUE TITLE
导入：失败（文件格式错误或文件已损坏）

### ISSUE THREAD

**Issue by Sofronio** [studyzy/imewlconverter#55]
把QQ输入法4.7备份的词库放到本软件进行转换，输出格式是win10微软拼音，导入的时候如下提示：
导入：失败（文件格式错误或文件已损坏）
谢谢！

**Comment by studyzy** [comment]
导入的短语会放在最前面还是怎么？应该怎么样的顺序才不恶心呢？

**Comment by studyzy** [comment]
高级设置中有个词频生成设置，可以改成你希望的词频。
