### ISSUE TITLE
可以参考这个repo添加搜狗v3词库

### ISSUE THREAD

**Issue by h4x3rotab** [studyzy/imewlconverter#56]
https://github.com/h4x3rotab/Sogou-User-Dict-Converter

**Comment by tmxkn1** [comment]
[**@h4x3rotab**](https://github.com/h4x3rotab) commented on [Oct 7, 2018, 2:26 PM GMT+1](https://github.com/studyzy/imewlconverter/issues/56#issue-367554523 "2018-10-07T13:26:32Z - Replied by Github Reply Comments"):
> [https://github.com/h4x3rotab/Sogou-User-Dict-Converter](https://github.com/h4x3rotab/Sogou-User-Dict-Converter)

读python无能 o_o

把你的代码复制到pycharm 5.0.4里各种报错啊。比如：
54行的[`return f'LString(size={self.size}, string="{self.string}")'`](https://github.com/h4x3rotab/Sogou-User-Dict-Converter/blob/9498d762921074a21e9f91907692e60b9163eb93/parse.py#L54) `f`后面直接加string pycharm不认可。
还有`ReadUint32()`，`ReadUint16()`显示unknown reference..

**Comment by studyzy** [comment]
已更新代码。谢谢，非常感谢！
