### ISSUE TITLE
谁有微软拼音自学习词库的导入导出算法？

### ISSUE THREAD

**Issue by studyzy** [studyzy/imewlconverter#58]
目前深蓝词库转换只支持微软拼音的“自定义用户短语”的导入导出，而用户自定义短语的词库量支持很有限，如果能够支持自学习词库就更好了。谁有微软拼音自学习词库的导入导出实现啊？

**Comment by jssda** [comment]
我就等着这个呢
大佬加油0.0

**Comment by weigaow** [comment]
同样等着呢

**Comment by RoderickQiu** [comment]
同样等着呢 也许哪天看看

**Comment by RoderickQiu** [comment]
![图片](https://user-images.githubusercontent.com/42290260/57576370-f1104a00-7490-11e9-8773-3b00388c56ff.png)
使用WinHex的Unicode UTF-16 LE模式读取了自学习字符 但别的暂时还不清楚 没研究
@studyzy 可以研究一下？

**Comment by studyzy** [comment]
> ![图片](https://user-images.githubusercontent.com/42290260/57576370-f1104a00-7490-11e9-8773-3b00388c56ff.png)
> 使用WinHex的Unicode UTF-16 LE模式读取了自学习字符 但别的暂时还不清楚 没研究
> @studyzy 可以研究一下？

我一般也是用WinHex分析的，不过这个比较难，搞不定。期待高手或者微软内部人员提供支持。

**Comment by liangwang1985** [comment]
微软拼音用户词提取：
位置： %USERPROFILE%\AppData\Roaming\Microsoft\InputMethod\Chs\ChsPinyinUDL.dat
用户词偏移：2400h
用户词数量：12-15字节的int值
每个用户词结构长度：60字节，
    用户词长度：（60字节中的）第10个字节byte值
    用户词：（60字节中的）第13个字节开始，长度为【用户词长度】*2字节， 编码是utf16


python3导出用户词代码如下：

import sys
import os
import platform

def str2sysstr(strout):
    sysstr = platform.system()
    if(sysstr =="Windows"):
        return strout.encode("gbk")
    else:
        return strout.encode("utf-8")


if __name__ == '__main__':
    if len(sys.argv)==2:
        user_word_file = sys.argv[1] 
    else:
        user_word_file = os.environ['USERPROFILE'] + "\AppData\Roaming\Microsoft\InputMethod\Chs\ChsPinyinUDL.dat"
    if not os.path.exists(user_word_file):
        print("file:",user_word_file,"not exist\n\n")
        print("use example")
        print( "user_word_exporter.exe")
        print( "                       : paser %USERPROFILE%\AppData\Roaming\Microsoft\InputMethod\Chs\ChsPinyinUDL.dat" )
        print( "user_word_exporter.exe  dat_file_name")
        print( "                       : paser dat_file_name")
        sys.exit(1)
    fp = open(user_word_file,"rb")
    userword = open("user_word_microsoft_pinyin.txt","at")
    data = fp.read()
    cnt = int.from_bytes(data[12:16], byteorder='little', signed=False)
    user_word_base = 0x2400
    for i in range(cnt):
        cur_idx = user_word_base + i * 60
        word_len = int.from_bytes(data[cur_idx + 10:cur_idx + 11], byteorder='little', signed=False)
        #word = str(data[cur_idx + 12:cur_idx + 12 + word_len * 2 ], encoding = "utf-16")
        word = data[cur_idx + 12 : cur_idx + 12 + word_len * 2 ].decode("utf-16")
        userword.write(word+"\n")
        #userword.writelines([str2sysstr(word) + "\n"])
        #print(str2sysstr(word))
    fp.close()
    userword.close()

**Comment by RoderickQiu** [comment]
> 
> 
> 微软拼音用户词提取：
> 位置： %USERPROFILE%\AppData\Roaming\Microsoft\InputMethod\Chs\ChsPinyinUDL.dat
> 用户词偏移：2400h
> 用户词数量：12-15字节的int值
> 每个用户词结构长度：60字节，
> 用户词长度：（60字节中的）第11个字节的byte值
> 用户词：（60字节中的）第13个字节开始，长度为【用户词长度】*2字节， 编码是utf16
> 
> python3导出用户词代码如下：
> `
> import sys
> import os
> import platform
> 
> def str2sysstr(strout):
> sysstr = platform.system()
> if(sysstr =="Windows"):
> return strout.encode("gbk")
> else:
> return strout.encode("utf-8")
> 
> if **name** == '**main**':
> if len(sys.argv)==2:
> user_word_file = sys.argv[1]
> else:
> user_word_file = os.environ['USERPROFILE'] + "\AppData\Roaming\Microsoft\InputMethod\Chs\ChsPinyinUDL.dat"
> if not os.path.exists(user_word_file):
> print("file:",user_word_file,"not exist\n\n")
> print("use example")
> print( "user_word_exporter.exe")
> print( " : paser %USERPROFILE%\AppData\Roaming\Microsoft\InputMethod\Chs\ChsPinyinUDL.dat" )
> print( "user_word_exporter.exe dat_file_name")
> print( " : paser dat_file_name")
> sys.exit(1)
> fp = open(user_word_file,"rb")
> userword = open("user_word_microsoft_pinyin.txt","at")
> data = fp.read()
> cnt = int.from_bytes(data[12:16], byteorder='little', signed=False)
> user_word_base = 0x2400
> for i in range(cnt):
> cur_idx = user_word_base + i * 60
> word_len = int.from_bytes(data[cur_idx + 10:cur_idx + 11], byteorder='little', signed=False)
> #word = str(data[cur_idx + 12:cur_idx + 12 + word_len * 2 ], encoding = "utf-16")
> word = data[cur_idx + 12 : cur_idx + 12 + word_len * 2 ].decode("utf-16")
> userword.write(word+"\n")
> #userword.writelines([str2sysstr(word) + "\n"])
> #print(str2sysstr(word))
> fp.close()
> userword.close()
> `
> 
> ![image](https://user-images.githubusercontent.com/27110951/64310356-61a81d00-cfd2-11e9-99b3-de667f5c2c13.png)

似乎很棒，虽然缩进什么的没了。@studyzy 期待整合。

**Comment by happyTonakai** [comment]
今天把搜狗的词库转成win10的自定义短语，整个输入法都废了，各种常规词都打不出来…… 只能期待自学习词库了

**Comment by Yeba** [comment]
实测上面python可以用，转化为c#代码：
    class Win10PinYinReader {
        private string path; // ChsPinyinUDL.dat

        public Win10PinYinReader(string path) {
            this.path = path;
            if (!File.Exists(path))
                throw new FileNotFoundException();
        }

        //read ChsPinyinUDL.dat to list
        public List<string> read() {
            List<string> re = new List<string>();
            FileStream fp = File.OpenRead(path);
            int user_word_base = 0x2400;
            //get word num
            byte[] bytes = new byte[50];
            fp.Seek(12, SeekOrigin.Begin);
            fp.Read(bytes, 0, 4);
            int cnt = bytesToIntLittle(bytes, 0, 4);
            //get each word
            for (int i = 0; i < cnt; i++) {
                int cur_idx = user_word_base + i * 60;
                //get word len
                fp.Seek(cur_idx + 10, SeekOrigin.Begin);
                fp.Read(bytes, 0, 1);
                int wordLen = bytesToIntLittle(bytes, 0, 1);
                //get word
                fp.Seek(cur_idx + 12, SeekOrigin.Begin);
                fp.Read(bytes, 0, wordLen * 2);
                string word = Encoding.Unicode.GetString(bytes, 0, wordLen * 2);
            }

            return re;
        }

        //to utf8 txt
        public static void write(string path, List<string> ss) {
            FileStream outf = File.OpenWrite(path);
            foreach (var s in ss) {
                byte[] bytes = Encoding.UTF8.GetBytes((s + "\n").ToCharArray());
                outf.Write(bytes);
            }

            outf.Flush();
            outf.Close();
        }

        /// <summary>
        /// 小端数字到int
        /// </summary>
        /// <param name="src">数组</param>
        /// <param name="offset">从数组offset开始</param>
        /// <param name="len">长len个字节</param>
        /// <returns></returns>
        public static int bytesToIntLittle(byte[] src, int offset, int len) {
            int value = 0, sf = 0;
            for (; len > 0; offset++, len--, sf += 8)
                value |= (src[offset] & 0xFF) << sf;
            return value;
        }
    }

使用：
        static void Main(string[] args) {
            string path = "../../../ChsPinyinUDL.dat";
            string outpath = "../../../out.txt";
            Win10PinYinReader reader = new Win10PinYinReader(path);
            List<string> ss = reader.read();
            Win10PinYinReader.write(outpath,ss);
        }
@studyzy 希望整合

**Comment by HowcanoeWang** [comment]
上面@liangwang1985的python代码把词库转成了
```
嗷嗷哭
阿呵	
啊啊灼灼
...
```
这种形式，然后我直接利用pypinyin库，直接在后面生成拼音，产生了如下的txt文件，符合rime的yaml词库的格式
```
嗷嗷哭	ao ao ku	1
阿呵	a he	1
啊啊灼灼	a a zhuo zhuo	1
```
直接把导出的结果复制到xxxx.dict.yaml里面即可直接被当作词库

改进后的python代码(方便直接复制)：
```python
import sys
import os
import platform
import pypinyin

def str2sysstr(strout):
    sysstr = platform.system()
    if(sysstr =="Windows"):
        return strout.encode("gbk")
    else:
        return strout.encode("utf-8")

if __name__ == '__main__':
    if len(sys.argv)==2:
        user_word_file = sys.argv[1]
    else:
        user_word_file = os.environ['USERPROFILE'] + "\AppData\Roaming\Microsoft\InputMethod\Chs\ChsPinyinUDL.dat"
    
    if not os.path.exists(user_word_file):
        print("file:",user_word_file,"not exist\n\n")
        print("use example")
        print( "user_word_exporter.exe")
        print( " : paser %USERPROFILE%\AppData\Roaming\Microsoft\InputMethod\Chs\ChsPinyinUDL.dat" )
        print( "user_word_exporter.exe dat_file_name")
        print( " : paser dat_file_name")
        sys.exit(1)
    
    fp = open(user_word_file,"rb")
    userword = open("user_word_microsoft_pinyin.txt","at")
    data = fp.read()
    cnt = int.from_bytes(data[12:16], byteorder='little', signed=False)
    user_word_base = 0x2400
    for i in range(cnt):
        cur_idx = user_word_base + i * 60
        word_len = int.from_bytes(data[cur_idx + 10:cur_idx + 11], byteorder='little', signed=False)
        word = data[cur_idx + 12 : cur_idx + 12 + word_len * 2 ].decode("utf-16")
        # -=-=-=-=-=-=--=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=
        # reference: https://www.jb51.net/article/167461.htm
        #
        # convert character to pinyin
        pinyin_str = '\t'
        pinyin_list = pypinyin.pinyin(word, style=pypinyin.NORMAL)
        # return [['shi'], ['shu'], ['ji'], ['shi'], ['zhang']]
        for i, py in enumerate(pinyin_list):   
            pinyin_str += py[0]
            if i+1 != word_len:  # not the last word, add space behind
                pinyin_str += ' '
        one_line = word + pinyin_str + '\t1'
        print(word + pinyin_str + '\t1')
        # -=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=-=---=-=-=-=-=-=-=-=
        userword.write(one_line + "\n")

    fp.close()
    userword.close()
```
然后还用pyinstaller打包了一份exe，给那些没有装python的同学(win10_x64位)，py文件和exe文件在zip里面
[pinyin.zip](https://github.com/studyzy/imewlconverter/files/4365598/pinyin.zip)
@RoderickQiu @studyzy 期待整合

**Comment by RoderickQiu** [comment]
亲测可用 看来问题解决了 强！

**Comment by ayanamist** [comment]
有没有导入的算法呀，上面的好像都是导出的？

**Comment by studyzy** [comment]
自学习词库导出成其他词库我已经在最新代码中集成了，现在正在看能不能把其他词库导入到自学习词库中，如果这个能解决，才是真正解决了微软拼音的词库问题。

**Comment by studyzy** [comment]
已解决，欢迎大家使用2.8版

**Comment by ayanamist** [comment]
试用了一下，确实支持了，不过2w条的限制还是有点烦人，能否把一个大文件自动切分成多个文件呀？

**Comment by studyzy** [comment]
@ayanamist 我在代码里面是那么做了，后来发现切割后的多个文件虽然提示导入成功，可惜微软拼音并不支持后来的导入，仍然以第一个2W为准。所以代码里面我就取消了，直接抛出异常。

**Comment by ayanamist** [comment]
我自己的7w条词库没验证是否实际成功，但我后来手工导入了一个词条，能确认一开始这个词没办法直接出现，导入后输入拼音就能出现了，说明导入肯定是成功了

**Comment by studyzy** [comment]
那我把分拆成多个文件启用吧！

**Comment by studyzy** [comment]
@ayanamist 已更新，您试一试？

**Comment by ayanamist** [comment]
我已经导入了不少数据了，不想清掉重来了，看看后面有没有人反馈吧？

**Comment by happyTonakai** [comment]
我感觉导入多个文件确实不起作用，在 `AppData\Roaming\Microsoft\InputMethod\Chs` 中的 `ChsPinyinUDL.dat` 文件大小始终是 1181kb，和分割后导入的 dat 文件大小一致，并且再从微软拼音导出自学习词汇同样是这个大小

**Comment by ayanamist** [comment]
你们试一下，每导入一个文件，就把设置窗口整体关闭再打开，再导入下一个

**Comment by studyzy** [comment]
不管导入的是2W还是4W，6W，最后我们再导出，导出只有2W。所以微软拼音自学习词库只支持2W。

**Comment by wsbblyy** [comment]
> 上面@liangwang1985的python代码把词库转成了
> 
> ```
> 嗷嗷哭
> 阿呵	
> 啊啊灼灼
> ...
> ```
> 
> 这种形式，然后我直接利用pypinyin库，直接在后面生成拼音，产生了如下的txt文件，符合rime的yaml词库的格式
> 
> ```
> 嗷嗷哭	ao ao ku	1
> 阿呵	a he	1
> 啊啊灼灼	a a zhuo zhuo	1
> ```
> 
> 直接把导出的结果复制到xxxx.dict.yaml里面即可直接被当作词库
> 
> 改进后的python代码(方便直接复制)：
> 
> ```python
> import sys
> import os
> import platform
> import pypinyin
> 
> def str2sysstr(strout):
>     sysstr = platform.system()
>     if(sysstr =="Windows"):
>         return strout.encode("gbk")
>     else:
>         return strout.encode("utf-8")
> 
> if __name__ == '__main__':
>     if len(sys.argv)==2:
>         user_word_file = sys.argv[1]
>     else:
>         user_word_file = os.environ['USERPROFILE'] + "\AppData\Roaming\Microsoft\InputMethod\Chs\ChsPinyinUDL.dat"
>     
>     if not os.path.exists(user_word_file):
>         print("file:",user_word_file,"not exist\n\n")
>         print("use example")
>         print( "user_word_exporter.exe")
>         print( " : paser %USERPROFILE%\AppData\Roaming\Microsoft\InputMethod\Chs\ChsPinyinUDL.dat" )
>         print( "user_word_exporter.exe dat_file_name")
>         print( " : paser dat_file_name")
>         sys.exit(1)
>     
>     fp = open(user_word_file,"rb")
>     userword = open("user_word_microsoft_pinyin.txt","at")
>     data = fp.read()
>     cnt = int.from_bytes(data[12:16], byteorder='little', signed=False)
>     user_word_base = 0x2400
>     for i in range(cnt):
>         cur_idx = user_word_base + i * 60
>         word_len = int.from_bytes(data[cur_idx + 10:cur_idx + 11], byteorder='little', signed=False)
>         word = data[cur_idx + 12 : cur_idx + 12 + word_len * 2 ].decode("utf-16")
>         # -=-=-=-=-=-=--=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=
>         # reference: https://www.jb51.net/article/167461.htm
>         #
>         # convert character to pinyin
>         pinyin_str = '\t'
>         pinyin_list = pypinyin.pinyin(word, style=pypinyin.NORMAL)
>         # return [['shi'], ['shu'], ['ji'], ['shi'], ['zhang']]
>         for i, py in enumerate(pinyin_list):   
>             pinyin_str += py[0]
>             if i+1 != word_len:  # not the last word, add space behind
>                 pinyin_str += ' '
>         one_line = word + pinyin_str + '\t1'
>         print(word + pinyin_str + '\t1')
>         # -=-=-=-=-=-==-=-=-=-=-==-=-=-=-=-=-=---=-=-=-=-=-=-=-=
>         userword.write(one_line + "\n")
> 
>     fp.close()
>     userword.close()
> ```
> 
> 然后还用pyinstaller打包了一份exe，给那些没有装python的同学(win10_x64位)，py文件和exe文件在zip里面
> [pinyin.zip](https://github.com/studyzy/imewlconverter/files/4365598/pinyin.zip)
> @RoderickQiu @studyzy 期待整合

可用, NB
