### ISSUE TITLE
对不含词频的Rime 词库转换问题

### ISSUE THREAD

**Issue by ecc29** [studyzy/imewlconverter#60]
只测试了最新的2.4.1版，此版在读取不含词频的Rime 词库（txt 文件）时会返回出错 “Index was outside the bounds of the array.” 试验用编辑器在原词库文件每个词条后添加一个1后转换成功。既然程序的高级设置里有关于词频的设置，所以猜测这是一个文件内容读取时的bug。

**Comment by zgdlime** [comment]
这个问题是要解决。
