### ISSUE TITLE
转换来自chinese-pyim的同行并列多个词时，只留下第一个，丢失其后所有

### ISSUE THREAD

**Issue by Oend** [studyzy/imewlconverter#61]
最近我下载了来自https://github.com/tumashu/pyim-greatdict的词库，其内含有如下形式：

fu-lan 弗兰 腐烂 佛兰 夫兰 福兰 俯览 富兰 扶栏 付兰 芙兰 浮滥 富镧 馥兰 扶兰 复兰 浮岚 抚栏 弗蘭 赋兰 负韊 负籣

转换到搜狗txt的结果里，只保留了'fu'lan 弗兰

这是一个号称拥有330万词条的词库，其转换结果最终只有240万条，丢失了90万条，看起来全部都是这类同行并列词条

作者是否有可能修复这个问题呢？或者任何人可以提供一些解决这一问题的方案呢？

**Comment by studyzy** [comment]
已修复。未发布版本。可自行编译。
