### ISSUE TITLE
请问怎样利用该转换器实现 win10 微软拼音的字序跟智能ABC的字序一致? 我是盲打用户.

### ISSUE THREAD

**Issue by GreatFireWall** [studyzy/imewlconverter#62]
例如智能ABC hui7 是"辉"字, 而微软拼音是 hui3

**Comment by GreatFireWall** [comment]
![image](https://user-images.githubusercontent.com/4510984/48419256-70e38300-e792-11e8-8914-f3ae5bb6eeaf.png)
补个bug

**Comment by studyzy** [comment]
智能ABC哪里可以导入导出词库？我没找到。本软件目前是不支持智能ABC的

**Comment by GreatFireWall** [comment]
你好, 不是智能ABC导入导出, 而是导入跟智能ABC 的字序一样的词库或者自定义短语库, 这个库(txt)网上可以找到, 你需要我也可以提供. 问题是如上图这种格式怎么导入?

**Comment by studyzy** [comment]
你先做个文本替换，把=替换成，然后在深蓝词库转换中选择自定义，就可以了。

**Comment by GreatFireWall** [comment]
@studyzy 你好, 我替换后得到同样的结果, 请问还需要其他设置吗?

![image](https://user-images.githubusercontent.com/4510984/48930317-b4748480-ef2a-11e8-9a71-2c8f7d8addae.png)

**Comment by studyzy** [comment]
麻烦把源词库发给我一下，我本地试一试。

**Comment by GreatFireWall** [comment]
https://gist.github.com/GreatFireWall/d62c30b0058cae5d42421798af86057d

**Comment by studyzy** [comment]
zhe,17,鹧
zhe,18,褶
zhe,19,蜇
zhe,20,赭
zhei,1,这
zhen,,真
zhen,,阵
zhen,,镇
zhen,,针
zhen,,震
zhen,,枕
zhen,,振
zhen,,斟
zhen,,珍
zhen,,甄
zhen,,砧
zhen,,臻
zhen,,贞
zhen,,侦
zhen,,疹
zhen,,诊
zhen,,圳
zhen,,蓁
zhen,,浈
zhen,,缜
zhen,,桢
zhen,,榛
zhen,,轸
zhen,,赈
zhen,,胗
zhen,,朕
zhen,,祯
zhen,,畛
zhen,,稹
zhen,,鸩
zhen,,箴
zhen,,椹
zheng,1,正
zheng,2,整

有的行有词频，有的行没有。这不统一，所以没办法处理。

**Comment by GreatFireWall** [comment]
对不起. 这不是词频, 而是指在页面的第几个字, 如 "zhe,1,这" 表示输入"zhe" 第一个就是 "这" , 10代表数字0, 即第十个, 超过10的代表下一页, 如 11 代表第2页的第一个, 21代表第3页的第一个. 

另外, 这里你理解为词频, 而它代表的实则为词序, 那么我修正这部分缺失后, 转换器是否还能正常工作?
