### ISSUE TITLE
无法转换日期和时间

### ISSUE THREAD

**Issue by ztj1993** [studyzy/imewlconverter#63]
我现在 Win10 自定义短语中，定义了日期和时间的选项，导出后，无法转为自定义文本，同时，自定义文本无法转为 Win10 自定义短语词库。

我是希望将自定义文本转为 Win10 自定义短语词库。

一下文本不会生效，仅仅方便调试：
```
crq %yyyy%-%MM%-%dd% 1234
csj %HH%:%mm%:%ss% 1
```

**Comment by studyzy** [comment]
非文字可能无法支持，只有手动添加了。
