### ISSUE TITLE
命令行的支持不是很好

### ISSUE THREAD

**Issue by StevenPZChan** [studyzy/imewlconverter#64]
首先谢谢楼主的工具。
本人的使用背景是在Linux环境下使用Rime输入五笔，所以想扩充词库，比如移植搜狗细胞词库。
不过Linux下只能使用命令行来使用该工具，双系统切来切去也不是很方便。
然后我发现-o:rime时-ct:wubi没有作用，还是生成的拼音，粗略研究了一下代码也没找出是什么原因。
还有命令行暂时还不能生成词频。

---

**Comment by studyzy** [comment]
推荐用最新发布的版本。
我在Linux命令行下运行：
dotnet ImeWlConverterCmd.dll -i:pyjj ./8.txt -o:rime ./rime.txt -ct:wubi
没有什么问题，导出数据为五笔。
