### ISSUE TITLE
能否增加对微软五笔字库的支持？

### ISSUE THREAD

**Issue by dazuocn** [studyzy/imewlconverter#67]
微软五笔的格式有相关的软件支持，源码如下：
https://gitee.com/xionghuaidong/public/tree/master/downloads
谢谢

**Comment by studyzy** [comment]
自定义功能中，可以选择自定义词库的编码，是可以支持微软五笔的。

**Comment by tabooms** [comment]
新学五笔的萌新，不懂编程……网上没有找到微软五笔的编码规则，斗胆向大佬提问……如果我想将微软五笔词库导出，该怎么设置自定义……
