### ISSUE TITLE
无法生成win10微软拼音(自定义短语)

### ISSUE THREAD

**Issue by RoyCao1995** [studyzy/imewlconverter#69]
我用的搜狗的自定义短语源文件，可以生成微软拼音和必应输入法自定义短语文件，可是不管用哪个都无法生成win10微软拼音的**.dat文件**，所有的错误提示都是如下
<img width="406" alt="win10" src="https://user-images.githubusercontent.com/28476284/51372665-e2480500-1b38-11e9-9735-b16b4ed0409f.png">

**Comment by studyzy** [comment]
麻烦提供一下您的源词库，我本地调试一下是什么原因导致的。

**Comment by BDZNH** [comment]
@studyzy 
你好，我这里生成的微软拼音的词库无法导入，系统为最新的 `Win10 1809 [版本 10.0.17763.316]`，
导出选项为“win10微软拼音(自定义短语)”，词库是搜狗官网下载的，我放到这里了[https://share.weiyun.com/5pnVSLx](https://share.weiyun.com/5pnVSLx)


系统才装上没几天，错误如下：
![image](https://user-images.githubusercontent.com/17548735/53461526-cb6fc900-3a7b-11e9-8c71-f3bd422fa6fe.png)

**Comment by studyzy** [comment]
是自定义短语，不是自学习词汇。
