### ISSUE TITLE
搜狗PC转华宇拼音只成功了一次

### ISSUE THREAD

**Issue by lingex** [studyzy/imewlconverter#70]
搜狗PC词库转华宇拼音第一次成功了，之后将搜狗词库初始化过，再导出的就转不了了，一直发生错误。

**Comment by studyzy** [comment]
不明白，如果第一次能成功，怎么可能第二次就不成功了，如果能提供词库，我复现一下最好。

**Comment by lingex** [comment]
两次词库不同，第二次的是把搜狗词库清空了重新整理再导出，就转不成功了。词库如何给你？
