### ISSUE TITLE
拼音加加的支持坏掉了

### ISSUE THREAD

**Issue by Ex-mortal** [studyzy/imewlconverter#71]
最新的2.4版，拼音加加格式的词库无法转换出来，而换成1.2版就可以转换。
可能是因为拼音加加太老，现在已经没什么人用了吧。

**Comment by studyzy** [comment]
经过测试，我这里没有问题啊。能否给出你的源词库给我？我本地调试一下。

**Comment by Ex-mortal** [comment]
@studyzy 
[古陶瓦基础词库（8万词）_搜狗词频.txt](https://github.com/studyzy/imewlconverter/files/2922776/8._.txt)

**Comment by studyzy** [comment]
@Ex-mortal 你把这个txt文件另存为UTF-8编码即可正常转换了。
