### ISSUE TITLE
无法转为Gboard格式的字库

### ISSUE THREAD

**Issue by LUAN-Z** [studyzy/imewlconverter#72]

**Comment by studyzy** [comment]
Gboard没发现有词库导入导出的功能啊！不知道Gboard词库是什么样的。

**Comment by CeresCa** [comment]
@studyzy Gboard正式版支持导入导出了，格式是zip文件（文件名没限制），里面包含一个 dictionary.txt ，
dictionary.txt 中格式如下
```
# Gboard Dictionary version:1
# From OS
jia	➕	zh
yi	一	zh
yiyiyituan	一一一团	zh
yiqiguodao	一七国道	zh
yiwan	一万	zh
yixia	一下	zh
```

**Comment by studyzy** [comment]
@CeresCa 我在应用宝里面下载了Gboard，在设置中没有看到词库导入导出的选项呢？

**Comment by CeresCa** [comment]
@studyzy 我用Google play下载的版本是有的

![](https://i.imgur.com/AHkO80z.png)

![](https://i.imgur.com/MuKHyin.png)

**Comment by studyzy** [comment]
你用什么工具翻墙的？我 SS已经被墙了。我的版本确实比你的老。

**Comment by peaceshi** [comment]
> 你用什么工具翻墙的？我 SS已经被墙了。我的版本确实比你的老。

你需要加入gboard beta测试计划。
字典格式是默认的Android 系统个人字典格式。
不过是有区域区分的。比如en_US和zh_CN两类字典。
具体你试一下就懂了

ssr：
https://rocket.abyss.moe/auth/login
