### ISSUE TITLE
词频

### ISSUE THREAD

**Issue by dccmmtop** [studyzy/imewlconverter#75]
软件中有通过百度搜索获取的词频，那么这种获取词频的方式是直接把词汇放到百度引擎中搜索，然后获取搜索的结果数量吗？

我从搜狗官网下载的词库，好像都不带词频信息，请问有什么好办法获取比较靠谱的词频吗？

**Comment by studyzy** [comment]
是的。就是你说的这种方法。我也没有更靠谱的获得词频的方法了。

**Comment by dccmmtop** [comment]
@studyzy  我之前用的也是这种办法，只是百度上限好像是 1亿， 那些常见的词汇都能达到这个量。就没法比较了
