### ISSUE TITLE
Linux 获取帮助

### ISSUE THREAD

**Issue by dccmmtop** [studyzy/imewlconverter#78]
![image](https://user-images.githubusercontent.com/17303988/56569915-7cae5d80-65ec-11e9-8e31-64728cf7ba18.png)

**Comment by studyzy** [comment]
是不是 dotnet core 安装的版本不对？

**Comment by studyzy** [comment]
dotnet --info

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by royaso** [comment]
这不就是？没转义嘛，我在macos下也出现过

**Comment by studyzy** [comment]
以后在Ubuntu下编译一个版本出来发布，应该就不会有同样问题了。
