### ISSUE TITLE
增加可运行的文件

### ISSUE THREAD

**Issue by chloe899** [studyzy/imewlconverter#8]
你好，建议把打包后的可执行文件加入到项目中，这样使用的人不作自己编译也可以用了

**Comment by tanliang** [comment]
这里有编译好的 https://code.google.com/p/imewlconverter/downloads/list

**Comment by chloe899** [comment]
好的，谢谢

**Comment by chloe899** [comment]
不过google要翻墙

**Comment by shawkynasr** [comment]
Dear Hanks,
      You can download form this link:

https://copy.com/OGNUkSrB8dPYZVf6

----
Kind regards,
*Shawky Nasr, Ph.D. Student*

Department of Educational Technology
Faculty of Education
Beijing Normal University
Beijing 100875, P. R. China

**Comment by chloe899** [comment]
好的，谢谢你

我已经自己编译了，谢谢

**Comment by studyzy** [comment]
本网站的Release中就可以下载：
https://github.com/studyzy/imewlconverter/releases

**Comment by shawkynasr** [comment]
不客气

​祝好！
邵基​
