### ISSUE TITLE
命令行，c参数的编码文件是什么格式

### ISSUE THREAD

**Issue by royaso** [studyzy/imewlconverter#80]
例如要将一个qpyd词库转换为自定义格式的文本词库，拼音之间逗号分割，拼音和词之间空格分割，不显示词频，同时使用自定义的编码文件code.txt命令如下：
深蓝词库转换.exe -i:qpyd D:\a.qpyd -o:self D:\zy.txt "-f:213, nyyn" -c:D:\code.txt

**Comment by studyzy** [comment]
汉字<Tab>编码
新版本中会包含该解释。
