### ISSUE TITLE
输出的词库类型是否可以支持搜狗细胞词库 scel

### ISSUE THREAD

**Issue by zzh1996** [studyzy/imewlconverter#82]
现在输入格式支持 scel，但是输出不支持，这个在技术上是否有什么困难？

我的需求是想把自定义的词组（txt 一行一个词）导入搜狗输入法

**Comment by zzh1996** [comment]
我已经搞定了。在 Windows 的搜狗输入法中导入 txt，然后在搜狗的数据目录下可以找到生成的 scel 文件，拷贝到 macOS 和手机上，就可以导入。

**Comment by studyzy** [comment]
恭喜！
