### ISSUE TITLE
是否支持 Mac 原生中文输入法？

### ISSUE THREAD

**Issue by linonetwo** [studyzy/imewlconverter#83]
看列表里没有列出。

**Comment by studyzy** [comment]
Mac原生中文输入法支持词库的导入导出吗？是什么样的格式？能否发一份给我。

**Comment by linonetwo** [comment]
谢谢你这么快就回复，我之所以搜到这个项目是因为我先中网上看到这篇文章 https://my.oschina.net/bieshixuan/blog/1863335 里面写了转换方案，我就想看看是不是有前辈已经发在 GitHub 上啦，然后就搜到你了～

可以参考一下这篇博客里的 swift 代码
