### ISSUE TITLE
提示：索引超出范围

### ISSUE THREAD

**Issue by 52fisher** [studyzy/imewlconverter#86]
系统：win10  1903
输入法：win10微软拼音-双拼-小鹤双拼（自定义方案）
操作：win10微软拼音 转 搜狗拼音txt
文件格式：dat
![图片](https://user-images.githubusercontent.com/32198215/58775800-f416da00-85f9-11e9-9055-9dedb530eac0.png)

自定义短语文件（改后缀dat）：
[UserDefinedPhrase.txt](https://github.com/studyzy/imewlconverter/files/3245843/UserDefinedPhrase.txt)

**Comment by studyzy** [comment]
额，这个文件里面一条数据都没有。所以没转换出来。

**Comment by 52fisher** [comment]
> 
> 
> 额，这个文件里面一条数据都没有。所以没转换出来。

可是很奇怪欸，我每次点击了 导出 之后，这个文件都会增大一些，并且提示导出成功。这个文件刚开始只放了两条短语，所以很小，现在有了几十条之后还是一样的结果。这就是我疑惑的地方
![图片](https://user-images.githubusercontent.com/32198215/58813970-72ee3000-8657-11e9-9862-39bcd8122b2a.png)

[UserDefinedPhrase.txt](https://github.com/studyzy/imewlconverter/files/3248340/UserDefinedPhrase.txt)

**Comment by studyzy** [comment]
不好意思，目前只支持汉字和拼音，对于特殊字符和非拼音，支持还不好。

**Comment by 52fisher** [comment]
> 不好意思，目前只支持汉字和拼音，对于特殊字符和非拼音，支持还不好。

希望在后面的计划中能够提供支持，win10 微软输入法的语义化做的不好，比如像打入 平方 这两个字，就不会出现平方这个符号。如果能够提供这类字符的录入，那么批量就很方便了，挂接上去基本上能战胜很多输入法了

**Comment by oneone1995** [comment]
![图片](https://user-images.githubusercontent.com/12215935/59013954-ecf80200-886d-11e9-87fc-318ec1add75d.png)
hi~我看是能出现平方的符号的
@52fisher

**Comment by 52fisher** [comment]
> ![图片](https://user-images.githubusercontent.com/12215935/59013954-ecf80200-886d-11e9-87fc-318ec1add75d.png)
> hi~我看是能出现平方的符号的
> @52fisher
双拼环境下，针对全拼的所有智能语义分析都是无效的，除非微软主动支持，否则目前只有通过自定义短语+固定位置的形式添加类似的词库进行挂载。小鹤的平方代码是pkfh，这样打出来的文字就失去了所有的助力，所以才希望能通过曲线救国的方式（至少目前是）

![image](https://user-images.githubusercontent.com/32198215/59014915-5711a680-8870-11e9-90aa-fec64efc4797.png)

**Comment by studyzy** [comment]
求小鹤双拼和拼音对照的码表，我网上找了一个，https://github.com/studyzy/imewlconverter/blob/master/src/ImeWlConverterCore/Resources/XiaoheShuangpin.txt
好像有些地方不对，如果谁能提供一个正确的就好了。

**Comment by 52fisher** [comment]
> 求小鹤双拼和拼音对照的码表，我网上找了一个，https://github.com/studyzy/imewlconverter/blob/master/src/ImeWlConverterCore/Resources/XiaoheShuangpin.txt
> 好像有些地方不对，如果谁能提供一个正确的就好了。

确实有很多不对的。我抽空校对一下

**Comment by studyzy** [comment]
[Release.zip](https://github.com/studyzy/imewlconverter/files/3268621/Release.zip)
在导出Win10微软拼音的时候提供小鹤双拼选项的支持，你看满足你的要求不。

**Comment by 52fisher** [comment]
> 
> 
> [Release.zip](https://github.com/studyzy/imewlconverter/files/3268621/Release.zip)
> 在导出Win10微软拼音的时候提供小鹤双拼选项的支持，你看满足你的要求不。

感谢，已经测试。确认支持。要是能够增加符号表情的支持就更好了

**Comment by studyzy** [comment]
支持的。在源里面可以选择Emoji作为源。格式是这样的：
Emoji +Tab键+汉语词汇
比如：
😀	大笑
🐘	大象
🐶	狗狗

**Comment by 52fisher** [comment]
> 
> 
> 支持的。在源里面可以选择Emoji作为源。格式是这样的：
> Emoji +Tab键+汉语词汇
> 比如：
> 😀	大笑
> 🐘	大象
> 🐶	狗狗

呃，我的意思是 在这个win10微软输入法的 自定义短语 里面能够增加符号、表情这类的转换，也就是上面所提到的 特殊字符和非拼音
![图片](https://user-images.githubusercontent.com/32198215/59148902-17e67f80-8a41-11e9-9119-f8ef6d21f043.png)
现在能够进行转换的就上面的  小鹤-拼音对照表 上面的内容 ，其他的符号比如平方之类的就无能为力了

**Comment by studyzy** [comment]
可以微调了一下代码，现在可以支持了。
源文件是：
😀	大笑
🐘	大象
🐶	狗狗
α	alpha
β	beta
²	平方
m³	立方米
π	pi
(✪ω✪)	大眼
(╥╯^╰╥)	cry

导入后的结果是：
![微软拼音](https://user-images.githubusercontent.com/1635408/59149264-f76cf400-8a45-11e9-9238-3d1c2553515b.png)

是你想要的效果吗？

**Comment by 52fisher** [comment]
> 
> 
> 可以微调了一下代码，现在可以支持了。
> 源文件是：
> 😀	大笑
> 🐘	大象
> 🐶	狗狗
> α alpha
> β beta
> ² 平方
> m³ 立方米
> π pi
> (✪ω✪) 大眼
> (╥╯^╰╥) cry
> 
> 导入后的结果是：
> ![微软拼音](https://user-images.githubusercontent.com/1635408/59149264-f76cf400-8a45-11e9-9238-3d1c2553515b.png)
> 
> 是你想要的效果吗？

bear hug！是我想要的效果。

**Comment by studyzy** [comment]
https://www.cnblogs.com/studyzy/p/10992274.html V2.6版已发布。
