### ISSUE TITLE
使用默认格式把搜狗细胞词库导入Rime无法生效

### ISSUE THREAD

**Issue by YogiLiu** [studyzy/imewlconverter#87]
默认输出格式如下：
```
 按引用传递  an  1
 按值传递    an  1
 安装调试    an  1
 包含文件    bao 1
 报警复位    bao 1
 本地存放地址    ben 1
```

用`:%s/\t\w\+\t1//g`去掉拼音和词频之后可以正常生效。

**Comment by studyzy** [comment]
未发现你说的这种情况，请问你的源词库是哪个细胞词库，目标词库是RIME拼音，是吧？

**Comment by YogiLiu** [comment]
计算机词汇、开发者专用词汇、数学专用词汇、Python相关词汇都有这种现象，目标词库是RIME小鹤双拼

**Comment by studyzy** [comment]
目标词库RIME只有选拼音的，没有小鹤双拼啊。

**Comment by YogiLiu** [comment]
额，我理解错了，输出命令参数有 -o:rime，是RIME拼音

**Comment by YogiLiu** [comment]
有可能不是这个项目的问题，因为我自己做的词库也有这个现象；如果是个例，应该可以关闭ISSUE了，thx！
