### ISSUE TITLE
搜狗输入法的txt词库是ANSI的怎么储存emoji表情不乱码

### ISSUE THREAD

**Issue by JinShichang** [studyzy/imewlconverter#90]
'la'zhen'di'niu'pi 🌶💉 💧 🐮 🍺 
比如这句 没法用ANSI储存 用UTF-8可以储存 但是搜狗打出来是乱码的
怎么解决

**Comment by studyzy** [comment]
搜狗输入法有个自定义短语功能。用这个就可以。
在深蓝词库转换中目标词库选“用户自定义短语”，然后选搜狗输入法，就可以了。

**Comment by JinShichang** [comment]
谢谢 解决了！
