### ISSUE TITLE
Mac 下运行转换生成 rime 格式时文件没有写入内容

### ISSUE THREAD

**Issue by soyaine** [studyzy/imewlconverter#91]
使用 [V2.6](https://github.com/studyzy/imewlconverter/releases/tag/V2.6) 的 Release_V2.6_Linux_MacOS.zip ，在 `dotnet-sdk-2.2.107-osx-x64` 环境下运行：

```
$ dotnet ImeWlConverterCmd.dll -i:sgpybin ./cibackup.bin -o:rime ./ci.txt
转换开始...
21:38:11
21:38:12	开始生成词频...
21:38:12	开始生成目标编码...
21:38:14	生成目标编码：22846/207206
21:38:17	生成目标编码：48989/207206
21:38:20	生成目标编码：75485/207206
21:38:23	生成目标编码：102037/207206
21:38:26	生成目标编码：128733/207206
21:38:29	生成目标编码：154765/207206
21:38:32	生成目标编码：181228/207206
21:38:35	生成目标编码：207022/207206
转换完成,共转换207206个
输入 -? 可获取帮助
```
生成的文件大小为 0 字节。
![image](https://user-images.githubusercontent.com/12845017/59438178-95393800-8e25-11e9-93e7-d7a75fe34830.png)

之后我尝试了其他格式，如 gg
```
$ dotnet ImeWlConverterCmd.dll -i:sgpybin ./cibackup.bin -o:ggpy ./gg.txt
转换开始...
21:44:43
21:44:43	开始生成词频...
21:44:44	开始生成目标编码...
21:44:46	生成目标编码：106964/207206
转换完成,共转换207206个
```
![image](https://user-images.githubusercontent.com/12845017/59438238-b6018d80-8e25-11e9-8366-639b99731ca9.png)
输出文件正确。

**Comment by studyzy** [comment]
这是因为你没有指定Rime词库的编码方式，所以编码生成失败。
-？说明中提到：
对于导出词库为Rime输入法的，可以通过-ct:pinyin/wubi/zhengma设置编码，也可通过-os:windows/macos/linux设置适用的操作系统
你可以通过添加参数-ct:pinyin 来指定Rime是拼音编码。

**Comment by soyaine** [comment]
@studyzy 谢谢回复。
这里编码格式有计划支持小鹤双拼（`-ct:flypy`）吗？

**Comment by soyaine** [comment]
已解决。
需要注意顺序，`-os:` 和 `-ct` 都需要写在最后。
