### ISSUE TITLE
搜狗五笔系统词库的bin文件能否转换

### ISSUE THREAD

**Issue by ulpyuxa** [studyzy/imewlconverter#98]
想问下搜狗五笔的系统词库能否转换？最近在整理词库，发现搜狗五笔的系统词库还不错，但是用2.6版本的深蓝无法转换，提示如下：
**不好意思，发生了错误：引发类型为“System.OutOfMemoryException”的异常**

不知道是什么原因呢？

**Comment by studyzy** [comment]
有些系统词库可单独额外处理，不在本软件的支持范围。
